# Generated by Django 5.2 on 2026-09-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QARun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict, help_text='{check_id: count}')),
                ('triage', models.JSONField(blank=True, default=dict, help_text='The AI triage: {headline, notes: [...]}')),
                ('triage_model', models.CharField(blank=True, default='', max_length=80)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QAFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('count', models.IntegerField()),
                ('previous', models.IntegerField(blank=True, help_text='The count in the last run that had this check.', null=True)),
                ('sample', models.JSONField(blank=True, default=list)),
                ('ids', models.JSONField(blank=True, default=list, help_text='Up to 1,000 row ids, for a fix request.')),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='qa.qarun')),
            ],
            options={
                'ordering': ['check_id'],
                'indexes': [models.Index(fields=['check_id', 'run'], name='qa_qafindin_check_i_a77f7a_idx')],
            },
        ),
    ]
