# Generated by Django 5.2 on 2026-07-13 20:21

import apps.webstore.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_stock_to_on_hand(apps, schema_editor):
    WebListing = apps.get_model('webstore', 'WebListing')
    for listing in WebListing.objects.all().iterator():
        listing.on_hand = listing.stock
        listing.reserved = 0
        listing.save(update_fields=['on_hand', 'reserved'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_item_item_checkedin_created_idx_and_more'),
        ('pos', '0009_qualityauditform'),
        ('webstore', '0002_order_orderline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weblisting',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='fb_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='fb_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='fb_posted_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='fb_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='on_hand',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weblisting',
            name='return_policy',
            field=models.CharField(choices=[('final_sale', 'Final sale'), ('return_48h_credit', '48-hour return → store credit')], default='final_sale', max_length=32),
        ),
        migrations.RunPython(copy_stock_to_on_hand, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weblisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('published', 'Published'), ('paused', 'Paused'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='ChannelPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('website', 'Website'), ('facebook_page', 'Facebook Page')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_publications', to='webstore.weblisting')),
            ],
            options={
                'ordering': ['channel', 'id'],
                'unique_together': {('listing', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_token', models.CharField(db_index=True, default=apps.webstore.models._public_status_token, max_length=48, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('staff_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('ready_for_pickup', 'Ready for pickup'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('staged_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direct_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_completed', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_confirmed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_reservations', to='inventory.item')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='webstore.weblisting')),
                ('pos_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_reservations', to='pos.cart')),
                ('staged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_staged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='webstore_re_status_4b7267_idx'), models.Index(fields=['listing', 'status'], name='webstore_re_listing_8d1f85_idx')],
            },
        ),
    ]
