# Generated by Django 5.2 on 2026-07-30 23:34

import apps.webstore.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_listing_reservation_channels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='', max_length=200)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=30)),
                ('public_token', models.CharField(db_index=True, default=apps.webstore.models._public_status_token, max_length=48, unique=True)),
                ('state', models.CharField(choices=[('needs_reply', 'Needs reply'), ('waiting_on_customer', 'Waiting on customer'), ('resolved', 'Resolved')], default='needs_reply', max_length=24)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('staff_unread', models.PositiveIntegerField(default=0)),
                ('customer_unread', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_conversations', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='webstore.weblisting')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='webstore.reservation')),
                ('staff_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_conversations_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_kind', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('system', 'System')], max_length=12)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webstore.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['state', 'last_message_at'], name='webstore_co_state_585bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['guest_email'], name='webstore_co_guest_e_c02827_idx'),
        ),
    ]
