# Generated by Django 5.2 on 2026-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
