# Generated by Django 5.2 on 2026-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0005_widen_reservation_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('pending_verification', 'Pending verification'), ('needs_reply', 'Needs reply'), ('waiting_on_customer', 'Waiting on customer'), ('resolved', 'Resolved')], default='needs_reply', max_length=24),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending verification'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('ready_for_pickup', 'Ready for pickup'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
