# Generated by Django 5.2 on 2026-08-25 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_parts_order_line_inspect'),
        ('pos', '0025_qualityaudit_updated_at'),
        ('webstore', '0015_conversation_customer_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['email'], name='webstore_re_email_63d1ce_idx'),
        ),
    ]
