# Generated by Django 5.2 on 2026-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_type',
            field=models.CharField(blank=True, choices=[('voluntary_resignation', 'Voluntary Resignation'), ('job_abandonment', 'Job Abandonment'), ('retirement', 'Retirement'), ('mutual_agreement', 'Mutual Agreement'), ('layoff', 'Layoff / Reduction in Force'), ('termination_for_cause', 'Termination for Cause'), ('termination_poor_performance', 'Termination – Poor Performance'), ('end_of_contract', 'End of Contract / Seasonal'), ('other', 'Other')], default='', max_length=40),
        ),
    ]
