# Generated by Django 5.2 on 2026-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_magic_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='hold_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='purpose',
            field=models.CharField(choices=[('sign_in', 'Sign in'), ('verify_email', 'Verify email'), ('verify_hold', 'Verify hold'), ('verify_thread', 'Verify thread'), ('reset_password', 'Reset password')], db_index=True, default='sign_in', max_length=32),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='thread_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=48),
        ),
    ]
