# Generated by Django 5.2 on 2026-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verified_holds_and_optional_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclinktoken',
            name='purpose',
            field=models.CharField(choices=[('sign_in', 'Sign in'), ('verify_email', 'Verify email'), ('verify_hold', 'Verify hold'), ('verify_thread', 'Verify thread'), ('reset_password', 'Reset password'), ('staff_reset_password', 'Staff reset password')], db_index=True, default='sign_in', max_length=32),
        ),
    ]
