# Generated by Django 5.2 on 2026-09-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='badge_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='badge_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='badge_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
