# Generated by Django 5.2 on 2026-10-06 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('role_changed', 'Role changed'), ('switched_off', 'Switched off'), ('switched_on', 'Switched on'), ('username_changed', 'Username changed'), ('password_link', 'Set-password link issued'), ('password_set', 'Password set from a link'), ('password_changed', 'Password changed'), ('locked_out', 'Locked out (too many wrong tries)')], db_index=True, max_length=24)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
