# Generated by Django 5.2 on 2026-08-31 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('definition', models.JSONField(default=dict)),
                ('trigger', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('on_demand', 'On demand')], default='daily', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('due_time', models.TimeField()),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.CharField(choices=[('pooled', 'Pooled — anyone on the list can complete it'), ('per_person', 'Per person — each assignee owes their own')], default='pooled', max_length=20)),
                ('assigned_role', models.CharField(blank=True, default='', max_length=40)),
                ('subject_pool', models.JSONField(blank=True, default=list)),
                ('is_blocking', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='hr.department')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='routines_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoutineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=32)),
                ('due_at', models.DateTimeField()),
                ('subject', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('missed', 'Missed')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine_runs', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_runs_completed', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='routines.routine')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('responses', models.JSONField(default=dict)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('has_critical_fail', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='routines.routine')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='routines.routinerun')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='routinerun',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_runs', to='routines.routinesubmission'),
        ),
        migrations.AddIndex(
            model_name='routinerun',
            index=models.Index(fields=['assigned_to', 'status', 'due_at'], name='routines_ro_assigne_256ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='routinerun',
            index=models.Index(fields=['status', 'due_at'], name='routines_ro_status_ca3afa_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinerun',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', False)), fields=('routine', 'period_key', 'assigned_to'), name='routines_run_period_user'),
        ),
        migrations.AddConstraint(
            model_name='routinerun',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', True)), fields=('routine', 'period_key'), name='routines_run_period_pooled'),
        ),
    ]
