# Generated by Django 5.2 on 2026-09-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_soft_delete_fields'),
        ('routines', '0003_biweekly_anchor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='kind',
            field=models.CharField(choices=[('checklist', 'Checklist'), ('section_tally', 'Section tally'), ('section_audit', 'Section cross-check'), ('owner_spot', 'Owner spot check')], default='checklist', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='late_after',
            field=models.CharField(choices=[('due_time', 'As soon as the hard nag starts'), ('end_of_day', 'End of the day it was due'), ('grace_days', 'After the grace days below')], default='end_of_day', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='remind_time',
            field=models.TimeField(blank=True, help_text='Soft nag: badges only. Blank starts at the top of the day.', null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='subject_source',
            field=models.CharField(choices=[('pool', 'From the subject pool below'), ('my_section', 'The sections this person owns'), ('other_section', "Somebody else's section, rotating")], default='pool', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='system_key',
            field=models.CharField(blank=True, help_text='Set on seeded program routines so code can find them. Blank for authored ones.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='verifies',
            field=models.ForeignKey(blank=True, help_text='Runner opens with a check that the last run of this routine was done to standard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to='routines.routine'),
        ),
        migrations.AddField(
            model_name='routinerun',
            name='generated',
            field=models.JSONField(blank=True, default=dict, help_text="Drawn at materialize time so the day's sample cannot be rerolled."),
        ),
        migrations.AlterField(
            model_name='routine',
            name='due_time',
            field=models.TimeField(blank=True, help_text='Hard nag: the app-bar alert. Blank means the nag waits for clock-out.', null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hr.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='routinerun',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='routines.section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='routines_section_name'),
        ),
    ]
