# Generated by Django 5.2 on 2026-09-02 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_drop_quality_audit'),
        ('routines', '0006_retail_qa_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='assignment',
            field=models.CharField(choices=[('pooled', 'Pooled: anyone on the list can complete it'), ('per_person', 'Per person: each assignee owes their own')], default='pooled', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='kind',
            field=models.CharField(choices=[('checklist', 'Checklist'), ('section_tally', 'Section tally'), ('section_audit', 'Section cross-check'), ('owner_spot', 'Owner spot check'), ('work_cycle', 'Work cycle')], default='checklist', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkCyclePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField()),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('shelf', 'Started a shelf check'), ('non_shelf', 'Started a non-shelf check'), ('dismissed', 'Dismissed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_cycle_prompts', to='pos.register')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_cycle_prompts', to='routines.routinesubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_cycle_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
    ]
