# Generated by Django 5.2 on 2026-09-18 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0021_routine_display_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkerflag',
            new_name='routines_ch_user_id_1d7924_idx',
            old_name='routines_fl_user_st_idx',
        ),
        migrations.RenameIndex(
            model_name='sectionassignmentevent',
            new_name='routines_se_section_627285_idx',
            old_name='routines_as_sec_day_idx',
        ),
        migrations.RenameIndex(
            model_name='sectionobservation',
            new_name='routines_se_section_f58ba5_idx',
            old_name='routines_ob_sec_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='sectionobservation',
            new_name='routines_se_actor_i_cb9db8_idx',
            old_name='routines_ob_act_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='sectionobservation',
            new_name='routines_se_in_base_cdc31f_idx',
            old_name='routines_ob_base_kind_idx',
        ),
        migrations.AddField(
            model_name='routine',
            name='gate_on_miss',
            field=models.BooleanField(default=False, help_text='Kiosk asks why when a run of this routine was missed, before the next clock-in. Superuser only.'),
        ),
        migrations.AddField(
            model_name='routinerun',
            name='miss_reason',
            field=models.CharField(blank=True, choices=[('forgot', 'Forgot'), ('no_time', 'Ran out of time'), ('called_in', 'Called in'), ('not_my_section', 'Not my section that day'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='routinerun',
            name='miss_reason_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routinerun',
            name='miss_reason_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_miss_reasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routinerun',
            name='miss_reason_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='due_time',
            field=models.TimeField(blank=True, help_text='When the run becomes overdue (amber). Blank means the nag waits for clock-out.', null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='kind',
            field=models.CharField(choices=[('checklist', 'Checklist'), ('section_tally', 'Section tally'), ('section_audit', 'Section cross-check'), ('owner_spot', 'Spot walk'), ('work_cycle', 'Register activity')], default='checklist', max_length=20),
        ),
    ]
