# Generated by Django 5.2 on 2026-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0022_kiosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekscoresnapshot',
            name='letter',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
