# Generated by Django 5.2 on 2026-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0024_cross_check_section_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionassignmentevent',
            name='kind',
            field=models.CharField(choices=[('owner', 'Section owner'), ('cross_checker', 'Cross-checker'), ('closed_for_day', 'Closed for the day'), ('reopened', 'Reopened'), ('cross_unblock', 'Cross-check unblocked')], max_length=20),
        ),
    ]
