# Generated by Django 5.2 on 2026-09-22 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0025_alter_sectionassignmentevent_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routinerun',
            name='routines_run_period_section',
        ),
        migrations.AddConstraint(
            model_name='routinerun',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False), ('section_scoped', True)), fields=('routine', 'period_key', 'section'), name='routines_run_period_section'),
        ),
    ]
