# Generated by Django 5.2 on 2026-09-22 19:31

from datetime import time

from django.db import migrations, models


# No system_key: program keys lock a routine for Retail QA grading, and this one is
# the owner's to reassign, pause, or retire. It is found by its kind instead.
KIND = 'bstock_pull'


def seed(apps, schema_editor):
    Routine = apps.get_model('routines', 'Routine')
    User = apps.get_model('accounts', 'User')
    Department = apps.get_model('hr', 'Department')
    if Routine.objects.filter(kind=KIND).exists():
        return
    office = Department.objects.filter(slug='office').first()
    row = Routine.objects.create(
        title='Pull B-Stock manifests',
        intro='Send your B-Stock login to the app, then pull the manifests for auctions ending soon.',
        kind=KIND,
        definition={'template_version': 1, 'sections': []},
        trigger='daily',
        weekdays=[],
        remind_time=time(8, 0),
        due_time=time(11, 0),
        late_after='end_of_day',
        grace_days=0,
        # A skipped day is gone: the pull only covers auctions ending in the next 36 hours.
        expire_rule='end_of_day',
        assignment='per_person',
        audience_type='person',
        assigned_role='Superuser',
        # Catalog grouping only; the audience is the named superusers.
        assigned_department_id=office.pk if office else None,
    )
    row.assigned_users.set(User.objects.filter(is_superuser=True, is_active=True))


def unseed(apps, schema_editor):
    Routine = apps.get_model('routines', 'Routine')
    RoutineSubmission = apps.get_model('routines', 'RoutineSubmission')
    routines = Routine.objects.filter(kind=KIND)
    # Submissions PROTECT their routine; clear them first (as RoutineViewSet.hard_delete does).
    RoutineSubmission.objects.filter(routine__in=routines).delete()
    RoutineSubmission.objects.filter(run__routine__in=routines).delete()
    routines.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0027_orphan_section_drafts'),
        ('accounts', '0008_kiosk'),
        ('hr', '0013_office_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='kind',
            field=models.CharField(choices=[('checklist', 'Checklist'), ('section_tally', 'Section tally'), ('section_audit', 'Section cross-check'), ('owner_spot', 'Spot walk'), ('work_cycle', 'Register activity'), ('bstock_pull', 'B-Stock manifest pull')], default='checklist', max_length=20),
        ),
        migrations.RunPython(seed, unseed),
    ]
