import type { RestorationPartsOrderDTO, RestorationPartsOrderLineDTO } from '../../../types/inventory.types';

export function partsOrderLineFixture(
  overrides: Partial<RestorationPartsOrderLineDTO> = {},
): RestorationPartsOrderLineDTO {
  return {
    id: 1,
    part_id: 1,
    description: 'Hinge',
    url: '',
    category: 'parts',
    qty: 1,
    unit_price: '6.00',
    unit_cost: '6.00',
    line_total: '6.00',
    inspect_verdict: '',
    inspect_note: '',
    ...overrides,
  };
}

export function partsOrderFixture(
  overrides: Partial<RestorationPartsOrderDTO> = {},
): RestorationPartsOrderDTO {
  return {
    id: 1,
    job: 9,
    job_sku: 'SKU-1',
    job_name: 'Xbox',
    job_stage: 'bench',
    job_starting_grade: '',
    job_final_grade: '',
    job_value_added: null,
    job_spent_parts_cost: null,
    job_dispositioned_at: null,
    name: 'Amazon hinge',
    target_grade: 'Working',
    target_grade_value: '45.00',
    shipping: '0.00',
    tax: '0.00',
    fees: '0.00',
    status: 'requested',
    denied_reason: '',
    est_shipping_days: null,
    expected_delivery_on: null,
    days_late: null,
    attention: 'approval',
    requested_at: null,
    requested_by: null,
    requested_by_name: '',
    approved_at: null,
    approved_by: null,
    approved_by_name: '',
    purchased_at: null,
    purchased_by: null,
    purchased_by_name: '',
    received_at: null,
    received_by: null,
    received_by_name: '',
    review_state: 'ok',
    review_note: '',
    cancel_requested: false,
    cancel_requested_at: null,
    cancel_requested_by: null,
    cancel_requested_by_name: '',
    cancel_reason: '',
    queued_behind: null,
    queued_behind_name: '',
    replacement_id: null,
    replacement_name: '',
    refunded: false,
    item_count: 1,
    total: '12.00',
    parts_cost: '12.00',
    needs_review: false,
    lines: [],
    created_at: '2026-08-20T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
    ...overrides,
  };
}
