import type { NavItemDef } from './navTypes';

/** Single source of truth for staff sidebar links (post web_ui_cleanup). */
export const NAV_ITEM_CATALOG: Record<string, NavItemDef> = {
  dashboard: {
    id: 'dashboard',
    path: '/dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
  },
  timeClock: {
    id: 'timeClock',
    path: '/hr/time-clock',
    label: 'Time clock',
    icon: 'schedule',
  },
  orders: {
    id: 'orders',
    path: '/inventory/orders',
    label: 'Orders',
    icon: 'shoppingCart',
  },
  preprocessing: {
    id: 'preprocessing',
    path: '/inventory/preprocessing',
    label: 'Preprocessing',
    icon: 'article',
  },
  receiving: {
    id: 'receiving',
    path: '/inventory/receiving',
    label: 'Receiving',
    icon: 'localShipping',
  },
  processing: {
    id: 'processing',
    path: '/inventory/processing',
    label: 'Processing',
    icon: 'inventory',
  },
  finalization: {
    id: 'finalization',
    path: '/inventory/inbound',
    label: 'Finalization',
    icon: 'assignmentTurnedIn',
    navSearch: '?view=finalization',
  },
  disputes: {
    id: 'disputes',
    path: '/inventory/inbound',
    label: 'Disputes',
    icon: 'balance',
    navSearch: '?view=disputes',
  },
  searchItems: {
    id: 'searchItems',
    path: '/inventory/items',
    label: 'Search items',
    icon: 'search',
    legacy: true,
  },
  inventoryWorkbench: {
    id: 'inventoryWorkbench',
    path: '/inventory/workbench',
    label: 'Catalog',
    icon: 'inventory',
  },
  floorplans: {
    id: 'floorplans',
    path: '/floor-ops/floorplans',
    label: 'Floorplans',
    icon: 'store',
  },
  quickReprice: {
    id: 'quickReprice',
    path: '/inventory/quick-reprice',
    label: 'Quick reprice',
    icon: 'localOffer',
  },
  vendors: {
    id: 'vendors',
    path: '/inventory/vendors',
    label: 'Vendors',
    icon: 'store',
  },
  posTerminal: {
    id: 'posTerminal',
    path: '/pos/terminal',
    label: 'Terminal',
    icon: 'pointOfSale',
  },
  posDrawers: {
    id: 'posDrawers',
    path: '/pos/drawers',
    label: 'Drawers',
    icon: 'accountBalance',
  },
  posCash: {
    id: 'posCash',
    path: '/pos/cash',
    label: 'Cash Management',
    icon: 'accountBalance',
  },
  posTransactions: {
    id: 'posTransactions',
    path: '/pos/transactions',
    label: 'Transactions',
    icon: 'inventory',
  },
  posPrintables: {
    id: 'posPrintables',
    path: '/pos/printables',
    label: 'Printables',
    icon: 'print',
  },
  posDeliveries: {
    id: 'posDeliveries',
    path: '/pos/deliveries',
    label: 'Deliveries',
    icon: 'localShipping',
  },
  auctions: {
    id: 'auctions',
    path: '/buying/auctions',
    label: 'Auctions',
    icon: 'gavel',
  },
  watchlist: {
    id: 'watchlist',
    path: '/buying/watchlist',
    label: 'Watchlist',
    icon: 'star',
  },
  assumptions: {
    id: 'assumptions',
    path: '/admin/assumptions',
    label: 'Assumptions',
    icon: 'factCheck',
    roles: ['Manager', 'Admin'],
  },
  posSetup: {
    id: 'posSetup',
    path: '/admin/pos-setup',
    label: 'POS setup',
    icon: 'tune',
    roles: ['Manager', 'Admin'],
  },
  onlineSalesListings: {
    id: 'onlineSalesListings',
    path: '/online-sales/listings',
    label: 'Listings',
    icon: 'storefront',
    roles: ['Manager', 'Admin'],
  },
  onlineSalesHolds: {
    id: 'onlineSalesHolds',
    path: '/online-sales/holds',
    label: 'Holds',
    icon: 'receiptLong',
    roles: ['Manager', 'Admin'],
  },
  onlineSalesCustomers: {
    id: 'onlineSalesCustomers',
    path: '/online-sales/customers',
    label: 'Customers',
    icon: 'people',
    roles: ['Manager', 'Admin'],
  },
  users: {
    id: 'users',
    path: '/admin/users',
    label: 'Employees',
    icon: 'supervisorAccount',
    roles: ['Admin'],
  },
  retailInbox: {
    id: 'retailInbox',
    path: '/admin/retail-inbox',
    label: 'Retail inbox',
    icon: 'receiptLong',
    roles: ['Admin'],
  },
  permissions: {
    id: 'permissions',
    path: '/admin/permissions',
    label: 'Permissions',
    icon: 'security',
    roles: ['Admin'],
  },
  settings: {
    id: 'settings',
    path: '/admin/settings',
    label: 'Settings',
    icon: 'settings',
    roles: ['Manager', 'Admin'],
  },
  labelStudio: {
    id: 'labelStudio',
    path: '/admin/label-studio',
    label: 'Label Studio',
    icon: 'localOffer',
    roles: ['Manager', 'Admin'],
  },
  restorationQueue: {
    id: 'restorationQueue',
    path: '/restoration/queue',
    label: 'Queue',
    icon: 'assignmentTurnedIn',
  },
  tars: {
    id: 'tars',
    path: '/restoration/tars',
    label: 'TARS',
    icon: 'build',
    openInNewWindow: true,
  },
  restorationPartsRequests: {
    id: 'restorationPartsRequests',
    path: '/restoration/parts-requests',
    label: 'Parts requests',
    icon: 'localShipping',
    roles: ['Manager', 'Admin'],
  },
  restorations: {
    id: 'restorations',
    path: '/inventory/restorations',
    label: 'Restorations',
    icon: 'assignmentReturned',
  },
  /** @deprecated Prefer `restorations` - kept for preference migration. */
  restorationReturns: {
    id: 'restorationReturns',
    path: '/inventory/restorations',
    label: 'Restorations',
    icon: 'assignmentReturned',
  },
  blogStudio: {
    id: 'blogStudio',
    path: '/blog-studio',
    label: 'Blog studio',
    icon: 'article',
    superuserOnly: true,
    openInNewWindow: true,
  },
  payrollHours: {
    id: 'payrollHours',
    path: '/admin/time-payroll',
    label: 'Time & payroll',
    icon: 'schedule',
    superuserOnly: true,
  },
  qualityAudit: {
    id: 'qualityAudit',
    path: '/admin/quality-audit',
    label: 'Quality Audit',
    icon: 'factCheck',
    roles: ['Manager', 'Admin'],
  },
  qualityAuditForms: {
    id: 'qualityAuditForms',
    path: '/admin/quality-audit/forms',
    label: 'QA Forms',
    icon: 'tune',
    superuserOnly: true,
  },
};
