import type { NavItemDef } from './navTypes';

/** Single source of truth for staff sidebar links (post web_ui_cleanup). */
export const NAV_ITEM_CATALOG: Record<string, NavItemDef> = {
  dashboard: {
    id: 'dashboard',
    path: '/dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
  },
  employees: {
    id: 'employees',
    path: '/hr/employees',
    label: 'Employees',
    icon: 'people',
  },
  orders: {
    id: 'orders',
    path: '/inventory/orders',
    label: 'Orders',
    icon: 'shoppingCart',
  },
  preprocessing: {
    id: 'preprocessing',
    path: '/inventory/preprocessing',
    label: 'Preprocessing',
    icon: 'article',
  },
  receiving: {
    id: 'receiving',
    path: '/inventory/receiving',
    label: 'Receiving',
    icon: 'localShipping',
  },
  processing: {
    id: 'processing',
    path: '/inventory/processing',
    label: 'Processing',
    icon: 'inventory',
  },
  finalization: {
    id: 'finalization',
    path: '/inventory/inbound',
    label: 'Finalization',
    icon: 'assignmentTurnedIn',
    navSearch: '?view=finalization',
  },
  disputes: {
    id: 'disputes',
    path: '/inventory/inbound',
    label: 'Disputes',
    icon: 'balance',
    navSearch: '?view=disputes',
  },
  searchItems: {
    id: 'searchItems',
    path: '/inventory/items',
    label: 'Search items',
    icon: 'search',
  },
  quickReprice: {
    id: 'quickReprice',
    path: '/inventory/quick-reprice',
    label: 'Quick reprice',
    icon: 'localOffer',
  },
  vendors: {
    id: 'vendors',
    path: '/inventory/vendors',
    label: 'Vendors',
    icon: 'store',
  },
  posTerminal: {
    id: 'posTerminal',
    path: '/pos/terminal',
    label: 'Terminal',
    icon: 'pointOfSale',
  },
  posDrawers: {
    id: 'posDrawers',
    path: '/pos/drawers',
    label: 'Drawers',
    icon: 'accountBalance',
  },
  posCash: {
    id: 'posCash',
    path: '/pos/cash',
    label: 'Cash Management',
    icon: 'accountBalance',
  },
  posTransactions: {
    id: 'posTransactions',
    path: '/pos/transactions',
    label: 'Transactions',
    icon: 'inventory',
  },
  auctions: {
    id: 'auctions',
    path: '/buying/auctions',
    label: 'Auctions',
    icon: 'gavel',
  },
  watchlist: {
    id: 'watchlist',
    path: '/buying/watchlist',
    label: 'Watchlist',
    icon: 'star',
  },
  assumptions: {
    id: 'assumptions',
    path: '/admin/assumptions',
    label: 'Assumptions',
    icon: 'factCheck',
    roles: ['Manager', 'Admin'],
  },
  posSetup: {
    id: 'posSetup',
    path: '/admin/pos-setup',
    label: 'POS setup',
    icon: 'tune',
    roles: ['Manager', 'Admin'],
  },
  users: {
    id: 'users',
    path: '/admin/users',
    label: 'Users',
    icon: 'supervisorAccount',
    roles: ['Admin'],
  },
  customers: {
    id: 'customers',
    path: '/admin/customers',
    label: 'Customers',
    icon: 'people',
    roles: ['Admin'],
  },
  permissions: {
    id: 'permissions',
    path: '/admin/permissions',
    label: 'Permissions',
    icon: 'security',
    roles: ['Admin'],
  },
  settings: {
    id: 'settings',
    path: '/admin/settings',
    label: 'Settings',
    icon: 'settings',
    roles: ['Manager', 'Admin'],
  },
  tars: {
    id: 'tars',
    path: '/restoration/tars',
    label: 'TARS',
    icon: 'build',
  },
};
