# Generated by Django 5.2 on 2026-09-30 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0100_catalog_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_item_ids', models.JSONField(blank=True, default=list)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CountScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('seq', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=64)),
                ('scanned_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('ok', 'OK'), ('already', 'Already scanned'), ('odd', 'Not on shelf per system'), ('unknown', 'Unknown code')], db_index=True, max_length=10)),
                ('item_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.item')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='stocktake.inventorycount')),
            ],
            options={
                'ordering': ['seq', 'id'],
                'indexes': [models.Index(fields=['count', 'code'], name='stocktake_scan_count_code')],
                'constraints': [models.UniqueConstraint(fields=('count', 'client_id'), name='stocktake_scan_client_once')],
            },
        ),
    ]
