# Generated by Django 5.2 on 2026-10-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def close_trial_counts(apps, schema_editor):
    """The first version's counts have no day. Close any left open so nothing scans into them."""
    from django.utils import timezone

    InventoryCount = apps.get_model('stocktake', 'InventoryCount')
    InventoryCount.objects.filter(day__isnull=True, status='open').update(status='closed', closed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_catalog_merge'),
        ('stocktake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='countscan',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countscan',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='day',
            field=models.DateField(blank=True, help_text='The store day this count is for (one per day).', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countscan',
            name='result',
            field=models.CharField(choices=[('ok', 'OK'), ('already', 'Already scanned'), ('odd', 'Not on shelf per system'), ('unknown', 'Tag not recognized'), ('bad_format', 'Not one of our tags')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pr', 'PR (processing)'), ('relocate', 'Relocate')], max_length=10)),
                ('label', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Scanning'), ('stopped', 'Stopped'), ('bad', 'Bad run')], db_index=True, default='open', max_length=10)),
                ('section_complete', models.BooleanField(default=False, help_text='The person said this section is fully scanned.')),
                ('note', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='stocktake.inventorycount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('kind', models.CharField(choices=[('not_sku', 'Not one of our tags'), ('not_recognized', 'Tag not recognized'), ('already_sold', 'Already sold'), ('not_on_shelf', 'Not on shelf per system'), ('already_scanned', 'Already scanned'), ('wrong_title', 'Wrong title'), ('wrong_tag', 'Bad tag'), ('price_high', 'Price too high'), ('price_low', 'Price too low'), ('no_tag', 'No tag'), ('wrong_section', 'Wrong section')], db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('pending', 'Needs an answer'), ('cleared', 'Cleared'), ('pr_cart', 'In a PR cart'), ('left', 'Left on the shelf'), ('relocate', 'In a relocate cart')], db_index=True, default='pending', max_length=10)),
                ('detail', models.CharField(blank=True, default='', help_text='What the scanner typed, e.g. the right title.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fix', models.CharField(blank=True, default='', max_length=20)),
                ('fix_note', models.CharField(blank=True, default='', max_length=300)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='stocktake.cart')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='stocktake.inventorycount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.item')),
                ('new_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.item')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='stocktake.countscan')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='stocktake.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='countscan',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='stocktake.run'),
        ),
        migrations.AddIndex(
            model_name='countscan',
            index=models.Index(fields=['count', 'item'], name='stocktake_scan_count_item'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='run',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='stocktake.section'),
        ),
        migrations.AddField(
            model_name='issue',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stocktake.section'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['count', 'section'], name='stocktake_run_count_section'),
        ),
        migrations.RunPython(close_trial_counts, migrations.RunPython.noop),
    ]
