# Generated by Django 5.2 on 2026-10-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_drop_template_columns'),
        ('stocktake', '0003_inventory_effort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrinkMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('back_stock', 'Back stock'), ('owner_took', 'Owner took'), ('sold_generic', 'Sold as generic'), ('stolen', 'Shrink: stolen'), ('broken', 'Shrink: broken'), ('scrap', 'Shrink: scrap')], db_index=True, max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('batch', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrink_marks', to='stocktake.inventorycount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.item')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-marked_at'],
                'constraints': [models.UniqueConstraint(fields=('count', 'item'), name='stocktake_shrink_mark_once')],
            },
        ),
    ]
