# Generated by Django 5.2 on 2026-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0004_shrink_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='action',
            field=models.CharField(choices=[('pending', 'Needs an answer'), ('cleared', 'Cleared'), ('pr_cart', 'In a PR cart'), ('left', 'Left on the shelf'), ('relocate', 'In a relocate cart'), ('kept', 'Kept here; old sale moved')], db_index=True, default='pending', max_length=10),
        ),
    ]
