# Generated by Django 5.2 on 2026-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0005_issue_action_kept'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='summary_cache',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
