# Generated by Django 5.2 on 2026-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0006_inventory_summary_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrinkmark',
            name='outcome',
            field=models.CharField(choices=[('back_stock', 'Back stock'), ('owner_took', 'Owner took'), ('sold_generic', 'Sold as generic'), ('sold_online', 'Sold online'), ('stolen', 'Shrink: stolen'), ('broken', 'Shrink: broken'), ('scrap', 'Shrink: scrap')], db_index=True, max_length=20),
        ),
    ]
