# Generated by Django 5.2 on 2026-08-25 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('restoration', 'Restoration'), ('processing', 'Processing')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('planned', 'Planned'), ('done', 'Done'), ('declined', 'Declined')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('unset', 'Unset'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='unset', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enhancement_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enhancement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EnhancementRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enhancement_request_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.enhancementrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='enhancementrequest',
            index=models.Index(fields=['area', 'status'], name='core_enhanc_area_dc4322_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancementrequest',
            index=models.Index(fields=['priority', 'target_date'], name='core_enhanc_priorit_bd57a6_idx'),
        ),
    ]
