# Generated by Django 5.2 on 2026-09-22 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appsettinghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('modality', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('effort', models.CharField(choices=[('off', 'Off'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('max', 'Max')], default='off', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['purpose'],
            },
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('xai', 'xAI'), ('google', 'Google')], max_length=20)),
                ('modality', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Added by hand'), ('discovered', 'Found by check')], default='manual', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'slug'],
            },
        ),
        migrations.RenameIndex(
            model_name='appsettinghistory',
            new_name='core_appset_key_96cd45_idx',
            old_name='core_appset_key_chg_idx',
        ),
        migrations.AddField(
            model_name='aiaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiaction',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.aimodel'),
        ),
    ]
