# Generated by Django 5.2 on 2026-09-23 21:43
"""Meta (Muse Spark) as a fourth AI provider, with its two models in the catalog.

Spark is the favourite for long, cheap data-correction runs (product_intelligence).
No action is switched to it here; the owner picks it per action in Settings > AI.
"""

from django.db import migrations, models

SPARK_MODELS = (
    ('muse-spark-1.3', 'Muse Spark 1.3'),
    ('muse-spark-1.3-contributor', 'Muse Spark 1.3 (contributor)'),
)


def add_spark_models(apps, schema_editor):
    AiModel = apps.get_model('core', 'AiModel')
    for slug, label in SPARK_MODELS:
        AiModel.objects.get_or_create(
            slug=slug,
            defaults={'label': label, 'provider': 'meta', 'modality': 'text', 'status': 'active', 'source': 'manual'},
        )


def remove_spark_models(apps, schema_editor):
    AiModel = apps.get_model('core', 'AiModel')
    AiModel.objects.filter(slug__in=[s for s, _ in SPARK_MODELS], provider='meta').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ai_models_from_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('xai', 'xAI'), ('google', 'Google'), ('meta', 'Meta')], max_length=20),
        ),
        migrations.RunPython(add_spark_models, remove_spark_models),
    ]
