# Generated by Django 5.2 on 2026-09-25 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ai_provider_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('preview', models.JSONField(blank=True, default=dict, help_text='{counts: {label: n}, changes: [text], sample: [row dicts]}')),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved, starting'), ('running', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('undone', 'Undone')], db_index=True, default='pending', max_length=10)),
                ('requested_by', models.CharField(blank=True, default='', help_text='Who staged it, e.g. claude:data_platform.', max_length=80)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.JSONField(blank=True, default=dict, help_text='{done, total, cursor}: the apply resumes from here.')),
                ('log', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
