# Generated by Django 5.2 on 2026-09-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_approval_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The day the numbers are about (the brief is read the morning after).', unique=True)),
                ('data', models.JSONField(default=dict)),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('writing', 'Writing'), ('ready', 'Ready'), ('failed', 'Failed')], default='writing', max_length=10)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to='core.contextsnapshot')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
