# Generated by Django 5.2 on 2026-09-28 20:21

from decimal import Decimal

from django.db import migrations, models

# Published list prices (USD per 1M tokens) found on 2026-09-28. Others stay blank (unknown) until set
# in Settings > AI.
KNOWN = {'claude-opus-5-5': (Decimal('4.00'), Decimal('20.00'))}


def seed(apps, schema_editor):
    AiModel = apps.get_model('core', 'AiModel')
    for slug, (inp, out) in KNOWN.items():
        AiModel.objects.filter(slug=slug, input_price__isnull=True).update(input_price=inp, output_price=out)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_supervisor_brief_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='input_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD per 1M input tokens. Blank = unknown.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='output_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD per 1M output tokens. Blank = unknown.', max_digits=8, null=True),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
