"""
Worked examples for the product standard (spec-v4, 2026-09-29). Each is a real product that a vet found done
wrong, with the answer written to the rules. The standardize prompt shows them; they teach the patterns that
rules alone did not: licensed names are not makers, brand casing, accessories and feature figures are not
specs, finishes are item details, sizes vs counts, impossible units, vague titles.

Keep every answer valid under `spec_rules` (allowed keys only) and the taxonomy (canon names only).
"""
from __future__ import annotations

EXAMPLES: list[dict] = [
    {
        'why': 'B1 and B3: the brand is the consumer brand on the box (Nerf, not the parent Hasbro); the license (Marvel) is the franchise.',
        'input': {'title': "Spiderman Nerf Strike 'N Splash Blaster", 'brand': 'Marvel Spiderman'},
        'answer': {'display_title': "Nerf Spider-Man Strike 'N Splash Water Blaster", 'short_name': 'Nerf Spider-Man Blaster',
                   'vector_text': 'nerf spider-man strike splash water blaster toy gun marvel superhero',
                   'brand': 'Nerf', 'model_number': '', 'category': 'Toys & games', 'subcategory': 'Outdoor & ride-ons',
                   'key_specs': {'toy_type': 'water blaster', 'franchise': 'Marvel', 'character': 'Spider-Man'},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'All-caps brand to its canonical form; a charger is Electronics (TAX-23); compatibility is not a voltage key.',
        'input': {'title': 'DEWALT 12V MAX/20V MAX Lithium Ion Battery Charger', 'brand': 'Dewalt', 'model': 'DCB107'},
        'answer': {'display_title': 'DeWalt 12V/20V MAX Lithium Ion Battery Charger', 'short_name': 'DeWalt Battery Charger',
                   'vector_text': 'dewalt battery charger lithium ion power tool 12v 20v max',
                   'brand': 'DeWalt', 'model_number': 'DCB107', 'category': 'Electronics',
                   'subcategory': 'Cables, chargers & power',
                   'key_specs': {'device_type': 'battery charger', 'compatible_with': '12V/20V MAX batteries'},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'A placeholder brand with a known product line takes the maker.',
        'input': {'title': 'Block Rocker Speaker', 'brand': 'Unbraded'},
        'answer': {'display_title': 'ION Audio Block Rocker Portable Speaker', 'short_name': 'ION Block Rocker Speaker',
                   'vector_text': 'ion audio block rocker portable bluetooth speaker pa party loud',
                   'brand': 'ION Audio', 'model_number': '', 'category': 'Electronics', 'subcategory': 'Audio',
                   'key_specs': {'device_type': 'portable speaker'}, 'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'The cube count is the size (G10), not piece_count; the finish color is an item detail; cube shelves are Furniture (TAX-55).',
        'input': {'title': '8-Cube Storage Organizer - Tobacco Oak', 'brand': 'Better Homes & Gardens'},
        'answer': {'display_title': 'Better Homes & Gardens 8-Cube Storage Organizer', 'short_name': 'BH&G 8-Cube Organizer',
                   'vector_text': 'better homes gardens cube organizer shelf storage bookcase cubby 8-cube',
                   'brand': 'Better Homes & Gardens', 'model_number': '', 'category': 'Furniture',
                   'subcategory': 'Storage furniture', 'key_specs': {'furniture_type': 'cube organizer', 'size': '8-cube'},
                   'item_details': {'color': 'Tobacco Oak'}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'Bed size is a product spec; counts are bare numbers (G11); the placeholder brand is Generic.',
        'input': {'title': 'Egyptian Cotton Sheet Set - King, 400tc', 'brand': 'Unbranded'},
        'answer': {'display_title': 'Egyptian Cotton Sheet Set King 400 Thread Count', 'short_name': 'Sheet Set King 400TC',
                   'vector_text': 'egyptian cotton sheet set bed sheets fitted flat pillowcases king 400',
                   'brand': 'Generic', 'model_number': '', 'category': 'Bedding & bath', 'subcategory': 'Sheets & pillowcases',
                   'key_specs': {'bedding_type': 'sheet set', 'bed_size': 'King', 'material': 'egyptian cotton',
                                 'thread_count': '400'},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'Feature figures (power levels) stay out of the title and specs (G9); capacity and wattage define a microwave.',
        'input': {'title': 'Cuisinart 1.3 Cu Ft Microwave Oven Countertop 1000W 11 Power Levels Black', 'brand': 'Cuisinart'},
        'answer': {'display_title': 'Cuisinart Countertop Microwave Oven 1.3 Cu Ft 1000W', 'short_name': 'Cuisinart Microwave 1.3cf',
                   'vector_text': 'cuisinart countertop microwave oven kitchen appliance 1.3 cu ft 1000w',
                   'brand': 'Cuisinart', 'model_number': '', 'category': 'Kitchen & dining', 'subcategory': 'Small appliances',
                   'key_specs': {'item_type': 'microwave', 'capacity': '1.3 cu ft', 'wattage': '1000W'},
                   'item_details': {'color': 'Black'}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'An included accessory (the 20oz travel cup) is not the product\'s capacity.',
        'input': {'title': 'Easy-to-Clean Blender - Glass Jar, 20oz Blend-n-Go Cup', 'brand': 'Oster'},
        'answer': {'display_title': 'Oster Easy-to-Clean Blender with Glass Jar', 'short_name': 'Oster Blender Glass Jar',
                   'vector_text': 'oster blender glass jar smoothie kitchen appliance blend-n-go glass',
                   'brand': 'Oster', 'model_number': '', 'category': 'Kitchen & dining', 'subcategory': 'Small appliances',
                   'key_specs': {'item_type': 'blender', 'material': 'glass'},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'A finish word (Brass) is an item detail, never the material or the title (G13).',
        'input': {'title': 'Threshold 24x36 Infinity Mantle Mirror Brass', 'brand': 'Threshold'},
        'answer': {'display_title': 'Threshold Infinity Mantle Mirror 24x36in', 'short_name': 'Threshold Mantle Mirror',
                   'vector_text': 'threshold infinity mantle mirror wall rectangular decor 24x36in',
                   'brand': 'Threshold', 'model_number': '', 'category': 'Home décor & lighting', 'subcategory': 'Mirrors',
                   'key_specs': {'decor_type': 'mantle mirror', 'size': '24x36in'},
                   'item_details': {'finish': 'Brass'}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'An impossible unit takes the one that fits (a 4in table is 4ft).',
        'input': {'title': '4in Long Height Adjustable Fold In Half Resin Table - Gray', 'brand': 'Osp Home Furnishings'},
        'answer': {'display_title': 'OSP Home Furnishings Adjustable Fold-in-Half Resin Table 4ft',
                   'short_name': 'OSP Folding Table 4ft',
                   'vector_text': 'osp home furnishings folding table fold in half adjustable height resin utility 4ft',
                   'brand': 'OSP Home Furnishings', 'model_number': '', 'category': 'Furniture', 'subcategory': 'Tables',
                   'key_specs': {'furniture_type': 'folding table', 'size': '4ft', 'material': 'resin'},
                   'item_details': {'color': 'Gray'}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'A 2-pack of separate figures is a count, not piece_count; each named character belongs in specs; the brand on the box (B1), not the parent Moose Toys.',
        'input': {'title': 'Goo Jit Zu Stretchy Knight Blazagon vs Squishy Corruptagon Figure Set 2pk', 'brand': 'Goo Jit Zu'},
        'answer': {'display_title': 'Goo Jit Zu Blazagon vs Corruptagon Figure Set 2pk', 'short_name': 'Goo Jit Zu Figures 2pk',
                   'vector_text': 'goo jit zu stretchy squishy action figures blazagon corruptagon kids toy 2',
                   'brand': 'Goo Jit Zu', 'model_number': '', 'category': 'Toys & games', 'subcategory': 'Figures',
                   'key_specs': {'toy_type': 'action figures', 'franchise': 'Goo Jit Zu',
                                 'character': 'Blazagon, Corruptagon', 'count': '2'},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'Apparel: size and color are item details; one product per style.',
        'input': {'title': "Women's High-Rise Skinny Jeans - Universal Thread Dark Wash 8", 'brand': 'Universal Thread'},
        'answer': {'display_title': "Universal Thread Women's High-Rise Skinny Jeans", 'short_name': 'Universal Thread Skinny Jean',
                   'vector_text': 'universal thread womens high rise skinny jeans denim pants',
                   'brand': 'Universal Thread', 'model_number': '', 'category': 'Apparel & accessories',
                   'subcategory': "Women's", 'key_specs': {'garment_type': 'skinny jeans', 'gender_or_age': 'women'},
                   'item_details': {'size': '8', 'color': 'Dark Wash'}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'A vague title: place by the recognizable brand, invent nothing, flag it.',
        'input': {'title': 'Deluxe Studio', 'brand': 'Blingle Bands'},
        'answer': {'display_title': 'Blingle Bands Deluxe Studio', 'short_name': 'Blingle Bands Studio',
                   'vector_text': 'blingle bands deluxe studio kids craft kit bracelet',
                   'brand': 'Blingle Bands', 'model_number': '', 'category': 'Toys & games', 'subcategory': 'Arts & crafts kits',
                   'key_specs': {}, 'item_details': {}, 'confidence': 'low', 'flags': 'vague_title'},
    },
    {
        'why': 'B2: a sub-line is not the brand (Hanes Premium -> Hanes, Premium stays in the title); a pack of 5 is a count; apparel size and color are item details.',
        'input': {'title': "Men's Comfort Tank Top Undershirt - White M, 5pk", 'brand': 'Hanes Premium'},
        'answer': {'display_title': "Hanes Premium Men's Comfort Tank Top Undershirt 5pk", 'short_name': 'Hanes Tank Undershirt 5pk',
                   'vector_text': 'hanes premium mens comfort tank top undershirt sleeveless cotton 5',
                   'brand': 'Hanes', 'model_number': '', 'category': 'Apparel & accessories', 'subcategory': 'Underwear & swim',
                   'key_specs': {'garment_type': 'tank top undershirt', 'gender_or_age': 'men', 'count': '5'},
                   'item_details': {'size': 'M', 'color': 'White'}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'B3: franchise is the top-level IP (Marvel), the line (Pop!) and the film (The Marvels) go in the title; B1: Funko is the brand.',
        'input': {'title': 'The Marvels Captain Marvel Pop! Vinyl Bobble Head', 'brand': 'Funko'},
        'answer': {'display_title': 'Funko Pop! The Marvels Captain Marvel Vinyl Bobblehead', 'short_name': 'Funko Pop Captain Marvel',
                   'vector_text': 'funko pop vinyl bobblehead figure captain marvel the marvels collectible marvel',
                   'brand': 'Funko', 'model_number': '', 'category': 'Toys & games', 'subcategory': 'Collectibles',
                   'key_specs': {'toy_type': 'vinyl bobblehead', 'franchise': 'Marvel', 'character': 'Captain Marvel'},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
    {
        'why': 'B4: a printed seller name stays the brand, flagged junk_brand, and stays off the tag; every stated measurement is a spec.',
        'input': {'title': 'IMossad Thickened Chair Cushion 20x20x2in Memory Foam', 'brand': 'IMossad'},
        'answer': {'display_title': 'IMossad Thickened Memory Foam Chair Cushion 20x20x2in', 'short_name': 'Chair Cushion 20x20in',
                   'vector_text': 'imossad thickened chair cushion seat pad memory foam 20x20x2in',
                   'brand': 'IMossad', 'model_number': '', 'category': 'Furniture', 'subcategory': 'Covers, pads & parts',
                   'key_specs': {'furniture_type': 'chair cushion', 'size': '20x20x2in', 'material': 'memory foam'},
                   'item_details': {}, 'confidence': 'high', 'flags': 'junk_brand'},
    },
    {
        'why': "B5: a retailer exclusive is never a spec or title text. B3: Gabby's Dollhouse is a license (franchise); the maker's brand is Spin Master.",
        'input': {'title': "Gabby's Dollhouse Meow-mazing Dollhouse (Walmart Exclusive)", 'brand': 'Spin Master'},
        'answer': {'display_title': "Spin Master Gabby's Dollhouse Meow-mazing Dollhouse Playset", 'short_name': "Gabby's Dollhouse Playset",
                   'vector_text': 'spin master gabbys dollhouse meow-mazing dollhouse playset kids pretend play cat',
                   'brand': 'Spin Master', 'model_number': '', 'category': 'Toys & games', 'subcategory': 'Dolls & playsets',
                   'key_specs': {'toy_type': 'dollhouse playset', 'franchise': "Gabby's Dollhouse"},
                   'item_details': {}, 'confidence': 'high', 'flags': ''},
    },
]
