# Generated by Django 5.2 on 2026-10-06 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_ai_model_prices'),
        ('hr', '0015_kiosk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('phone_digits', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('web', 'Careers page'), ('walk_in', 'Walk-in / paper'), ('email', 'Emailed resume'), ('referral', 'Referral'), ('other', 'Other')], default='web', max_length=20)),
                ('stage', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('interview_scheduled', 'Interview scheduled'), ('interviewed', 'Interviewed'), ('offer', 'Offer'), ('hired', 'Hired'), ('not_now', 'Not now')], db_index=True, default='new', max_length=24)),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_flags', models.PositiveSmallIntegerField(default=0)),
                ('sms_consent', models.BooleanField(default=False)),
                ('sms_consent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_consent_version', models.CharField(blank=True, default='', max_length=40)),
                ('sms_consent_text', models.TextField(blank=True, default='')),
                ('not_now_reason', models.CharField(blank=True, default='', max_length=20)),
                ('not_now_note', models.TextField(blank=True, default='')),
                ('not_now_stage', models.CharField(blank=True, default='', max_length=24)),
                ('not_now_email_status', models.CharField(blank=True, default='', max_length=10)),
                ('not_now_email_subject', models.CharField(blank=True, default='', max_length=200)),
                ('not_now_email_body', models.TextField(blank=True, default='')),
                ('not_now_at', models.DateTimeField(blank=True, null=True)),
                ('received_email_sent', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_applications', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.s3file')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Applied'), ('stage', 'Stage'), ('note', 'Note'), ('rating', 'Rating'), ('email', 'Email'), ('employee', 'Employee'), ('edit', 'Edit')], max_length=10)),
                ('from_stage', models.CharField(blank=True, default='', max_length=24)),
                ('to_stage', models.CharField(blank=True, default='', max_length=24)),
                ('text', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hiring.application')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('duties', models.JSONField(blank=True, default=list)),
                ('schedule', models.CharField(blank=True, default='', max_length=200)),
                ('hours', models.CharField(blank=True, default='', max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('full_or_part', 'Full or part time')], default='full_or_part', max_length=20)),
                ('pay_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pay_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pay_text', models.CharField(blank=True, default='', max_length=200)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('interview_questions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='hr.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='applications', to='hiring.job'),
        ),
    ]
