# Generated by Django 5.2 on 2026-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='looking_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='nice_to_have',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='physical',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='success',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='works_with',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
