# Generated by Django 5.2 on 2026-10-06 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ai_model_prices'),
        ('hiring', '0008_ai_jobs_role_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='kind',
            field=models.CharField(choices=[('offer', 'Offer'), ('interview', 'Interview'), ('created', 'Applied'), ('stage', 'Stage'), ('note', 'Note'), ('rating', 'Rating'), ('email', 'Email'), ('employee', 'Employee'), ('edit', 'Edit')], max_length=10),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='sent', max_length=10)),
                ('position', models.CharField(max_length=120)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employment_type', models.CharField(default='part_time', max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, default='', max_length=300)),
                ('respond_by', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('letter_subject', models.CharField(blank=True, default='', max_length=200)),
                ('letter_text', models.TextField()),
                ('acknowledgments', models.JSONField(blank=True, default=list)),
                ('consent_text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('signer_name', models.CharField(blank=True, default='', max_length=160)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('letter_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='hiring.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='hiring.job')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.s3file')),
                ('signed_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.s3file')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
