# Generated by Django 5.2 on 2026-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0009_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_practice',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
