# Generated by Django 5.2 on 2026-10-07 17:16

import django.db.models.deletion
from django.conf import settings
from datetime import timedelta

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Onboardings started before check-ins existed (v2.146.0) get theirs: 30, 60 and 90 days from the start."""
    Onboarding = apps.get_model('hiring', 'Onboarding')
    CheckIn = apps.get_model('hiring', 'CheckIn')
    setting = apps.get_model('core', 'AppSetting').objects.filter(key='hiring.careers').first()
    days = ((setting.value or {}).get('checkin') or {}).get('days') if setting and isinstance(setting.value, dict) else None
    days = days or [30, 60, 90]
    for onboarding in Onboarding.objects.exclude(status='cancelled'):
        if CheckIn.objects.filter(onboarding=onboarding).exists():
            continue
        CheckIn.objects.bulk_create([
            CheckIn(user_id=onboarding.user_id, manager_id=onboarding.manager_id, onboarding=onboarding, day=day,
                    due_date=onboarding.start_date + timedelta(days=day))
            for day in days
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ai_model_prices'),
        ('hiring', '0011_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Coming up'), ('done', 'Done'), ('skipped', 'Skipped')], db_index=True, default='scheduled', max_length=10)),
                ('form', models.JSONField(blank=True, default=dict)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('employee_comments', models.TextField(blank=True, default='')),
                ('close_onboarding', models.BooleanField(default=False)),
                ('skipped_reason', models.CharField(blank=True, default='', max_length=300)),
                ('manager_name', models.CharField(blank=True, default='', max_length=160)),
                ('employee_name', models.CharField(blank=True, default='', max_length=160)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.s3file')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_held', to=settings.AUTH_USER_MODEL)),
                ('manager_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.s3file')),
                ('onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='hiring.onboarding')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.s3file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
