# Generated by Django 5.2 on 2026-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0012_checkins'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='first_day_text_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='kind',
            field=models.CharField(choices=[('offer', 'Offer'), ('interview', 'Interview'), ('created', 'Applied'), ('stage', 'Stage'), ('note', 'Note'), ('rating', 'Rating'), ('email', 'Email'), ('text', 'Text'), ('employee', 'Employee'), ('edit', 'Edit')], max_length=10),
        ),
    ]
