# Generated by Django 5.2 on 2026-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0013_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtime',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='interview_times', to='hiring.job'),
        ),
        migrations.AlterField(
            model_name='interviewtime',
            name='kind',
            field=models.CharField(choices=[('open', 'Open for interviews'), ('block', 'Blocked')], max_length=5),
        ),
    ]
