# Generated by Django 5.2 on 2026-08-31 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_enhancement_request'),
        ('hr', '0004_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('sign', 'Sign'), ('acknowledge', 'Acknowledge'), ('read', 'Read')], default='sign', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.s3file')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('person', 'Person'), ('everyone', 'Everyone'), ('role', 'Role'), ('department', 'Department')], max_length=20)),
                ('assigned_role', models.CharField(blank=True, default='', max_length=40)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments_sent', to=settings.AUTH_USER_MODEL)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments', to='hr.department')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments_named', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=0)),
                ('x_pct', models.FloatField()),
                ('y_pct', models.FloatField()),
                ('w_pct', models.FloatField()),
                ('h_pct', models.FloatField()),
                ('kind', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('date', 'Date'), ('text', 'Text'), ('checkbox', 'Checkbox')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.document')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='documents.documentassignment')),
                ('signed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to='core.s3file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='documents.documentfield')),
                ('value_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_field_values', to='core.s3file')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='documents.documentrecipient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentrecipient',
            constraint=models.UniqueConstraint(fields=('assignment', 'user'), name='documents_recipient_assignment_user'),
        ),
        migrations.AddConstraint(
            model_name='documentfieldvalue',
            constraint=models.UniqueConstraint(fields=('recipient', 'field'), name='documents_fieldvalue_recipient_field'),
        ),
    ]
