# Generated by Django 5.2 on 2026-07-09 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('template', 'Template')], max_length=10)),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_backgrounds', to='core.s3file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_labels_created', to=settings.AUTH_USER_MODEL)),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_pdfs', to='core.s3file')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'kind'], name='labels_cust_is_acti_92192c_idx')],
            },
        ),
    ]
