# Generated by Django 5.2 on 2026-10-07 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=15)),
                ('kind', models.CharField(choices=[('job', 'Job application texts'), ('thriftplus', 'Thrift+ account texts'), ('news', 'Store news texts'), ('all', 'Every text (STOP)')], max_length=20)),
                ('key', models.CharField(help_text='Which text: opt_in, interview_booked, first_day…', max_length=40)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('held', 'Held (texting not live)'), ('sent', 'Sent'), ('failed', 'Could not send'), ('no_consent', 'Not sent: no consent'), ('opted_out', 'Not sent: they said stop'), ('no_number', 'Not sent: no mobile number'), ('practice', 'Not sent: practice run')], db_index=True, max_length=12)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('edited', models.BooleanField(default=False, help_text='Staff changed the words on the review screen.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_id', models.CharField(blank=True, default='', max_length=64)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TextConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Digits only, 10 for a US number.', max_length=15)),
                ('kind', models.CharField(choices=[('job', 'Job application texts'), ('thriftplus', 'Thrift+ account texts'), ('news', 'Store news texts'), ('all', 'Every text (STOP)')], max_length=20)),
                ('opted_in', models.BooleanField()),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('how', models.CharField(help_text='"Online job application", "Replied STOP", "Staff: Bill (they asked)".', max_length=160)),
                ('wording_version', models.CharField(blank=True, default='', max_length=40)),
                ('wording', models.TextField(blank=True, default='')),
                ('ref', models.CharField(blank=True, default='', help_text='What it came from, e.g. hiring.application:12.', max_length=80)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['phone', 'kind', '-at'], name='texting_tex_phone_3db8d8_idx')],
            },
        ),
    ]
