# Generated by Django 5.2 on 2026-10-08 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0002_backfill_job_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, help_text='Lower-case.', max_length=254)),
                ('kind', models.CharField(choices=[('job', 'Job application emails'), ('thriftplus', 'Thrift+ account emails'), ('news', 'Store news emails'), ('all', 'Every email (unsubscribe)')], max_length=20)),
                ('opted_in', models.BooleanField()),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('how', models.CharField(help_text='"Thrift+ sign-up (staff: name)", "Unsubscribe link".', max_length=160)),
                ('wording_version', models.CharField(blank=True, default='', max_length=40)),
                ('wording', models.TextField(blank=True, default='')),
                ('ref', models.CharField(blank=True, default='', help_text='What it came from, e.g. thriftplus.person:12.', max_length=80)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['email', 'kind', '-at'], name='texting_ema_email_bd2eac_idx')],
            },
        ),
    ]
