# Generated by Django 5.2 on 2026-07-02 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0002_floorplanasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanElementKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SlugField(help_text='Stable slug persisted in plan documents; immutable after create.', max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('category', models.CharField(default='Misc', max_length=64)),
                ('default_w', models.FloatField(help_text='Default width in inches.')),
                ('default_h', models.FloatField(help_text='Default depth in inches.')),
                ('fill_color', models.CharField(default='#9e9e9e', help_text='Hex fill, used when the element has no image.', max_length=7)),
                ('shape', models.CharField(choices=[('rect', 'Rectangle'), ('circle', 'Circle / ellipse')], default='rect', max_length=10)),
                ('corner_radius', models.FloatField(default=0, help_text='Corner radius in inches; only meaningful when shape=rect.')),
                ('resizable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded built-in; editable but not deletable, slug locked.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_image', models.ForeignKey(blank=True, help_text='Optional image preset applied to newly placed elements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_kinds', to='floorplan.floorplanasset')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
