# Generated by Django 5.2 on 2026-07-03 20:04

from django.db import migrations, models


def mark_seeded_wall(apps, schema_editor):
    FloorPlanElementKind = apps.get_model('floorplan', 'FloorPlanElementKind')
    FloorPlanElementKind.objects.filter(kind='wall').update(is_wall=True)


def unmark_seeded_wall(apps, schema_editor):
    FloorPlanElementKind = apps.get_model('floorplan', 'FloorPlanElementKind')
    FloorPlanElementKind.objects.filter(kind='wall').update(is_wall=False)


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0004_seed_element_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanelementkind',
            name='is_wall',
            field=models.BooleanField(default=False, help_text='Wall behavior: the raw height is the wall THICKNESS (survives rotation), resize drags change length only, and group scaling never fattens it.'),
        ),
        migrations.RunPython(mark_seeded_wall, unmark_seeded_wall),
    ]
