# Generated by Django 5.2 on 2026-02-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_fees_purchaseorder_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
