# Generated by Django 5.2 on 2026-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchaseorder_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Used - Good'), ('fair', 'Used - Fair'), ('salvage', 'Salvage'), ('mixed', 'Mixed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='retail_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
