# Generated by Django 5.2 on 2026-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_condition_purchaseorder_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
