# Generated by Django 5.2 on 2026-02-14 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_product_numbers(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    for idx, product in enumerate(Product.objects.order_by('id'), start=1):
        if not product.product_number:
            product.product_number = f'PRD-{idx:05d}'
            product.save(update_fields=['product_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder_manifest_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('salvage', 'Salvage'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='manifest_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.manifestrow'),
        ),
        migrations.AddField(
            model_name='item',
            name='processing_tier',
            field=models.CharField(choices=[('individual', 'Individual'), ('batch', 'Batch')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('new', 'New Product')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_rows', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='vendor_item_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='times_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_units_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('intake', 'Intake'), ('processing', 'Processing'), ('on_shelf', 'On Shelf'), ('sold', 'Sold'), ('returned', 'Returned'), ('scrapped', 'Scrapped'), ('lost', 'Lost')], default='intake', max_length=20),
        ),
        migrations.CreateModel(
            name='BatchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('total_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('salvage', 'Salvage'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_groups', to='inventory.manifestrow')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_batch_groups', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_groups', to='inventory.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_groups', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='batch_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.batchgroup'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('spec_template', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Change'), ('condition_change', 'Condition Change'), ('price_change', 'Price Change'), ('location_change', 'Location Change'), ('batch_processed', 'Batch Processed'), ('detached_from_batch', 'Detached From Batch'), ('sold', 'Sold'), ('returned', 'Returned'), ('lost', 'Lost'), ('found', 'Found'), ('note', 'Note')], max_length=30)),
                ('old_value', models.CharField(blank=True, default='', max_length=300)),
                ('new_value', models.CharField(blank=True, default='', max_length=300)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProductRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_item_number', models.CharField(max_length=100)),
                ('vendor_description', models.CharField(blank=True, default='', max_length=500)),
                ('last_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('times_seen', models.IntegerField(default=1)),
                ('last_seen_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_refs', to='inventory.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_refs', to='inventory.vendor')),
            ],
            options={
                'ordering': ['vendor', 'vendor_item_number'],
                'unique_together': {('vendor', 'vendor_item_number')},
            },
        ),
        migrations.RunPython(backfill_product_numbers, migrations.RunPython.noop),
    ]
