# Generated by Django 5.2 on 2026-02-16 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_condition_item_manifest_row_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='pricing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='pricing_stage',
            field=models.CharField(choices=[('unpriced', 'Unpriced'), ('draft', 'Draft'), ('final', 'Final')], default='unpriced', max_length=20),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
