# Generated by Django 5.2 on 2026-02-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_checked_in_at_item_checked_in_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestrow',
            name='ai_match_decision',
            field=models.CharField(blank=True, choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('uncertain', 'Uncertain'), ('new_product', 'New Product')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='ai_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='ai_suggested_brand',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='ai_suggested_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='ai_suggested_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='batch_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('salvage', 'Salvage'), ('unknown', 'Unknown')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='match_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='search_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
