# Generated by Django 5.2 on 2026-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_manifest_row_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscanhistory',
            name='source',
            field=models.CharField(choices=[('public_lookup', 'Public Lookup'), ('pos_terminal', 'POS Terminal'), ('audit_scan', 'Audit Scan')], default='public_lookup', max_length=20),
        ),
        migrations.CreateModel(
            name='TempLegacyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_sku', models.CharField(max_length=50, unique=True)),
                ('source_db', models.CharField(choices=[('db1', 'DB1 Legacy'), ('db2', 'DB2 Production')], max_length=10)),
                ('title', models.TextField()),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retail_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=20)),
                ('legacy_status', models.CharField(blank=True, default='', max_length=20)),
                ('retagged', models.BooleanField(db_index=True, default=False)),
                ('new_item_sku', models.CharField(blank=True, default='', max_length=20)),
                ('retagged_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['legacy_sku'],
                'indexes': [models.Index(fields=['source_db', 'retagged'], name='inventory_t_source__790f21_idx')],
            },
        ),
    ]
