# Generated by Django 5.2 on 2026-03-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_very_good_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetagLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_sku', models.CharField(db_index=True, max_length=50)),
                ('new_item_sku', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retagged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('retagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retag_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-retagged_at'],
            },
        ),
    ]
