# Generated by Django 5.2 on 2026-03-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_item_source_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='search_text',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
