# Generated by Django 5.2 on 2026-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_itemscanhistory_outcome_cart_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaglog',
            name='retagged_by',
        ),
        migrations.DeleteModel(
            name='TempLegacyItem',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ai_cleanup_generation',
            field=models.PositiveIntegerField(default=0, help_text='Incremented on cancel-ai-cleanup so in-flight batches skip writes.'),
        ),
        migrations.DeleteModel(
            name='RetagLog',
        ),
    ]
