# Generated by Django 5.2 on 2026-04-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_retag_scaffolding_and_cleanup_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='retail_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='batchgroup',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manifest/vendor retail per unit (legacy name unit_cost; not acquisition cost).', max_digits=10, null=True),
        ),
    ]
