# Generated by Django 5.2 on 2026-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_item_retail_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='misfit_sales_amt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share of misfit (no line item) sales attributed to this PO by mistracked retail.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='mistracked_retail',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PO retail_value minus sold retail and shrink estimate (non-negative).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shrink_retail_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated retail still lost to shrinkage after sold retail, from vendor shrinkage rate.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='avg_fulfillment',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sum of item retail on costed POs divided by sum of PO retail_value on those POs.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='avg_sell_through',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Retail value of sold items divided by retail value of all items on costed POs.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shrinkage_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='1 minus average sell-through (retail of sold items / retail of all items on costed POs).', max_digits=5, null=True),
        ),
    ]
