# Generated by Django 5.2 on 2026-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_merge_tgt_into_trget'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='misfit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Estimated fraction of PO retail gap attributable to untracked/misfit sales. Computed by recompute_cost_pipeline.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shrinkage_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Estimated true shrinkage rate after removing misfit/untracked share of missing retail. Computed by recompute_cost_pipeline.', max_digits=5, null=True),
        ),
    ]
