# Generated by Django 5.2 on 2026-04-15 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_retag_category_inheritance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'sold_at'], name='inventory_i_status_b37145_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'category'], name='inventory_i_status_a1a330_idx'),
        ),
    ]
