# Generated by Django 5.2 on 2026-04-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_po_est_shrink_remove_cost_pipeline_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('standardized', 'Standardized'), ('ai_imported', 'AI Imported'), ('review', 'Manual Review'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=0, help_text='0=standardize, 1=AI cleanup, 2=manual review')),
                ('manifest_headers', models.JSONField(blank=True, default=list)),
                ('header_signature', models.CharField(blank=True, default='', max_length=255)),
                ('standardization_formulas', models.JSONField(blank=True, default=dict)),
                ('template_name', models.CharField(blank=True, default='', max_length=200)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('standardized_at', models.DateTimeField(blank=True, null=True)),
                ('last_ai_import_at', models.DateTimeField(blank=True, null=True)),
                ('review_saved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing', to='inventory.purchaseorder')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preprocessing_orders', to='inventory.csvtemplate')),
            ],
            options={
                'verbose_name': 'Preprocessing Order',
                'verbose_name_plural': 'Preprocessing Orders',
            },
        ),
        migrations.CreateModel(
            name='PreprocessingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('condition', models.CharField(blank=True, default='', max_length=20)),
                ('retail_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_stage', models.CharField(choices=[('unpriced', 'Unpriced'), ('draft', 'Draft'), ('final', 'Final')], default='unpriced', max_length=20)),
                ('pricing_notes', models.TextField(blank=True, default='')),
                ('upc', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_item_number', models.CharField(blank=True, default='', max_length=100)),
                ('batch_flag', models.BooleanField(default=False)),
                ('search_tags', models.TextField(blank=True, default='')),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('ai_suggested_title', models.CharField(blank=True, default='', max_length=300)),
                ('ai_suggested_brand', models.CharField(blank=True, default='', max_length=200)),
                ('ai_suggested_model', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preprocessing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='inventory.preprocessingorder')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_rows', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['preprocessing_order', 'row_number'],
                'indexes': [models.Index(fields=['preprocessing_order', 'row_number'], name='inventory_p_preproc_5eb9ad_idx'), models.Index(fields=['purchase_order', 'row_number'], name='inventory_p_purchas_be5611_idx')],
                'constraints': [models.UniqueConstraint(fields=('preprocessing_order', 'row_number'), name='inventory_preproc_row_unique_order_rn')],
            },
        ),
    ]
