# Generated by Django 5.2 on 2026-04-29 20:26

import re

from django.conf import settings
from django.db import migrations, models


def backfill_po_vendor_cache_and_search(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    Vendor = apps.get_model('inventory', 'Vendor')
    for po in PurchaseOrder.objects.iterator(chunk_size=200):
        name = ''
        code = ''
        if po.vendor_id:
            v = Vendor.objects.filter(pk=po.vendor_id).only('name', 'code').first()
            if v:
                name = (v.name or '')[:200]
                code = (v.code or '')[:20]
        parts = [po.order_number or '', name, code, po.description or '']
        text = ' '.join(parts).lower()
        text = re.sub(r'\s+', ' ', text).strip()
        PurchaseOrder.objects.filter(pk=po.pk).update(
            vendor_name_cache=name,
            vendor_code_cache=code,
            search_text=text,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0024_preprocessing_staging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='search_text',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_code_cache',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name_cache',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-ordered_date'], name='inv_po_status_ordered_dt'),
        ),
        migrations.RunPython(backfill_po_vendor_cache_and_search, noop_reverse),
    ]
