# Generated by Django 5.2 on 2026-04-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0025_po_vendor_cache_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('mixed', 'Mixed'), ('damaged', 'Damaged')], default='', max_length=20)),
                ('issues', models.TextField(blank=True, default='')),
                ('pallet_count', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('draft_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_records_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_record', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bol', 'BOL'), ('truck', 'Truck'), ('pallet_side', 'Pallet Side')], max_length=20)),
                ('pallet_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('front', 'Front'), ('right', 'Right'), ('back', 'Back'), ('left', 'Left')], default='', max_length=10)),
                ('client_photo_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.receiving')),
                ('s3_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_attachments', to='core.s3file')),
            ],
            options={
                'indexes': [models.Index(fields=['receiving', 'kind'], name='inventory_r_receivi_b1e75a_idx'), models.Index(fields=['receiving', 'client_photo_id'], name='inventory_r_receivi_b6dd0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceivingPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_number', models.PositiveSmallIntegerField()),
                ('damaged', models.BooleanField(default=False)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='inventory.receiving')),
            ],
            options={
                'ordering': ['pallet_number'],
                'constraints': [models.UniqueConstraint(fields=('receiving', 'pallet_number'), name='uniq_receiving_pallet_number')],
            },
        ),
    ]
