# Generated by Django 5.2 on 2026-04-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_receiving_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_pallet_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected pallet count when ordering (optional).', null=True),
        ),
    ]
