# Generated by Django 5.2 on 2026-05-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_csvtemplate_vendor_signature_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='csvtemplate',
            name='inv_csvtpl_vendor_sig_idx',
        ),
    ]
