# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_ai_category_flat_manifest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingrow',
            name='ai_status',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"state": clean|soft_flagged|hard_flagged|recovered, "issues": [...]}',
            ),
        ),
    ]
