# Generated by Django 5.2 on 2026-05-01 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_preprocessingrow_ai_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dispute_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='dispute_pct_loss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dispute_type',
            field=models.CharField(blank=True, choices=[('broken', 'Broken'), ('undelivered', 'Undelivered')], default='', help_text='Item Processor dispute classification when status is scrapped/lost.', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemSwapAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapped_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_swap_audits', to='inventory.purchaseorder')),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_audits_as_source', to='inventory.manifestrow')),
                ('swapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_swap_audits', to=settings.AUTH_USER_MODEL)),
                ('target_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_audits_as_target', to='inventory.manifestrow')),
            ],
            options={
                'ordering': ['-swapped_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('source_manifest_row_ids', models.JSONField(default=list)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_merge_audits', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_merge_audits', to='inventory.purchaseorder')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_audits_as_target', to='inventory.product')),
            ],
            options={
                'ordering': ['-merged_at'],
            },
        ),
    ]
