# Generated by Django 5.2 on 2026-05-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_item_processor_disputes_and_audits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('unit_retail', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_stage', models.CharField(choices=[('unpriced', 'Unpriced'), ('draft', 'Draft'), ('final', 'Final')], default='unpriced', max_length=20)),
                ('pricing_notes', models.TextField(blank=True, default='')),
                ('batch_flag', models.BooleanField(default=False)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('condition', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('identifiers', models.JSONField(blank=True, default=dict)),
                ('taxonomy', models.JSONField(blank=True, default=dict)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('tracking', models.JSONField(blank=True, default=dict)),
                ('search_tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preprocessing_row', models.ForeignKey(blank=True, help_text='Source staging row ID at finalize-time (audit only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_bookmarks', to='inventory.preprocessingrow')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_bookmarks', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order', 'row_number'],
                'indexes': [models.Index(fields=['purchase_order', 'row_number'], name='inventory_p_purchas_7ac0b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('purchase_order', 'row_number'), name='inv_proc_bm_po_rn_unique')],
            },
        ),
    ]
