# Generated by Django 6.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0041_processing_row_canonical_denorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingDataBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[
                    ('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'),
                    ('failed', 'Failed'), ('blocked', 'Blocked'),
                ], db_index=True, default='pending', max_length=20)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('chunk_size', models.PositiveIntegerField(default=100)),
                ('max_items_per_chunk', models.PositiveIntegerField(default=500)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('created_items', models.PositiveIntegerField(default=0)),
                ('current_row_number', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='processing_data_build',
                    to='inventory.purchaseorder',
                )),
                ('created_by', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Processing data build',
                'verbose_name_plural': 'Processing data builds',
            },
        ),
    ]
