# Generated by Django 5.2 on 2026-05-08 16:44

from django.db import migrations, models


def forwards_fill_manifest_meta(apps, schema_editor):
    """
    Backfill ids 316-319 only after verifying ``order_number``.

    Copies manifest_filename / manifest_uploaded_at from ``core_s3file`` when ``manifest_id`` is set.
    manifest_row_count from ``manifest_preview['row_count']`` (else 0).
    manifest_category_count from compute_category_count(preview headers, preview rows).

    Legacy seeds may **undercount** categories vs a full-file scan - ``manifest_preview['rows']`` is only a sample.
    """

    from apps.inventory.services.manifest_meta import compute_category_count

    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    S3File = apps.get_model('core', 'S3File')

    expected_order_numbers = {
        316: 'AMZ0N-OQL-CCP4',
        317: 'C5TC0-OM1-A8R3',
        318: 'TRGET-O4U-QP68',
        319: 'TRGET-O2R-1K40',
    }

    for pk, expected_on in expected_order_numbers.items():
        po = PurchaseOrder.objects.filter(pk=pk).first()
        if not po or po.order_number != expected_on:
            continue
        if (
            po.manifest_filename is not None
            and po.manifest_uploaded_at is not None
            and po.manifest_row_count is not None
            and po.manifest_category_count is not None
        ):
            continue

        preview = po.manifest_preview or {}
        headers = preview.get('headers') or []
        rows = preview.get('rows') or []
        row_count = preview.get('row_count')
        if row_count is None:
            row_count = 0

        manifest_filename = None
        manifest_uploaded_at = None
        if po.manifest_id:
            s3 = S3File.objects.filter(pk=po.manifest_id).first()
            if s3:
                manifest_filename = s3.filename
                manifest_uploaded_at = s3.uploaded_at

        category_count = compute_category_count(headers, rows)

        PurchaseOrder.objects.filter(pk=pk).update(
            manifest_filename=manifest_filename,
            manifest_uploaded_at=manifest_uploaded_at,
            manifest_row_count=row_count,
            manifest_category_count=category_count,
        )


def forwards_fill_manifest_meta_reverse(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    PurchaseOrder.objects.filter(pk__in=(316, 317, 318, 319)).update(
        manifest_filename=None,
        manifest_uploaded_at=None,
        manifest_row_count=None,
        manifest_category_count=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_rename_processingrow_list_unit_price_shelf_price'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processingrow',
            new_name='inventory_p_purchas_bd399e_idx',
            old_name='inventory_p_purchas_qs_idx',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_category_count',
            field=models.IntegerField(
                blank=True,
                help_text='Distinct non-empty category column values snapshot from upload.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_row_count',
            field=models.IntegerField(
                blank=True,
                help_text='Row count snapshot from last manifest upload.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingrow',
            name='shelf_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Workspace-canonical shelf/tag unit price for Item Processor (queue + detail price field); seeded from preprocessing/finalize paths; processing mutations align Item.price to match; refresh_processing_rows_denorm does not overwrite from Item.price when manifest-linked.',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='processingrow',
            index=models.Index(fields=['manifest_row'], name='inventory_p_manifes_92a563_idx'),
        ),
        migrations.AddIndex(
            model_name='processingrow',
            index=models.Index(fields=['matched_product'], name='inventory_p_matched_4f88fc_idx'),
        ),
        migrations.RunPython(forwards_fill_manifest_meta, forwards_fill_manifest_meta_reverse),
    ]
