# Generated by Django 5.2 on 2026-05-08 20:43

import django.db.models.deletion
from django.db import migrations, models


WF_TO_PREPROCESS = {
    'draft': 'not_started',
    'standardized': 'standardized',
    'ai_imported': 'cleaned',
    'review': 'reviewing',
    'finalized': 'finalized',
}


def forwards_wave1_backfill(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    PreprocessingOrder = apps.get_model('inventory', 'PreprocessingOrder')
    CSVTemplate = apps.get_model('inventory', 'CSVTemplate')

    for prep in PreprocessingOrder.objects.select_related('purchase_order').iterator():
        po = PurchaseOrder.objects.filter(pk=prep.purchase_order_id).first()
        if not po:
            continue
        preview = po.manifest_preview or {}
        updates = {}

        last_ai = getattr(prep, 'last_ai_import_at', None)
        if last_ai is not None and po.ai_cleaned_at is None:
            updates['ai_cleaned_at'] = last_ai

        sig = preview.get('signature') or ''
        if sig and not (po.manifest_signature or '').strip():
            updates['manifest_signature'] = sig

        headers = preview.get('headers')
        if po.manifest_headers is None and headers is not None:
            updates['manifest_headers'] = list(headers) if not isinstance(headers, list) else headers

        if getattr(prep, 'template_id', None) and po.template_id is None:
            updates['template_id'] = prep.template_id

        tpl = None
        tid = prep.template_id or po.template_id
        if tid:
            tpl = CSVTemplate.objects.filter(pk=tid).first()

        if tpl:
            if not (po.template_name_cache or '').strip():
                updates['template_name_cache'] = tpl.name
            if not (po.template_header_signature_cache or '').strip():
                updates['template_header_signature_cache'] = tpl.header_signature or ''
            cm = tpl.column_mappings
            if cm is not None and not po.template_column_mappings_cache:
                updates['template_column_mappings_cache'] = cm
        elif (prep.template_name or '').strip() and not (po.template_name_cache or '').strip():
            updates['template_name_cache'] = prep.template_name

        prep_formulas = prep.standardization_formulas or {}
        if prep_formulas and not (po.standardization_formulas or {}):
            updates['standardization_formulas'] = dict(prep_formulas)

        wf = (getattr(prep, 'workflow_status', '') or '').strip()
        mapped = WF_TO_PREPROCESS.get(wf, 'not_started')
        if wf and mapped != 'not_started' and po.preprocess_status == 'not_started':
            updates['preprocess_status'] = mapped

        for field_po, field_prep in (
            ('standardized_at', 'standardized_at'),
            ('review_saved_at', 'review_saved_at'),
            ('finalized_at', 'finalized_at'),
        ):
            pv = getattr(prep, field_prep, None)
            if pv is not None and getattr(po, field_po, None) is None:
                updates[field_po] = pv

        if updates:
            PurchaseOrder.objects.filter(pk=po.pk).update(**updates)


def backwards_wave1_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_purchase_order_manifest_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_pallet_count',
            new_name='pallet_count',
        ),
        migrations.RenameField(
            model_name='receiving',
            old_name='pallet_count',
            new_name='received_pallet_count',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ai_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closeout_status',
            field=models.CharField(choices=[('open', 'Open')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='intake_dispute_status',
            field=models.CharField(choices=[('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manifest_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='preprocess_status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not started'),
                    ('standardized', 'Standardized'),
                    ('cleaned', 'Cleaned'),
                    ('reviewing', 'Reviewing'),
                    ('finalized', 'Finalized'),
                ],
                default='not_started',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='processing_dispute_status',
            field=models.CharField(choices=[('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='processing_status',
            field=models.CharField(choices=[('not_started', 'Not started')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receiving_status',
            field=models.CharField(choices=[('not_started', 'Not started')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='review_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='standardization_formulas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='standardized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_purchase_orders',
                to='inventory.csvtemplate',
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='template_column_mappings_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='template_header_signature_cache',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='template_name_cache',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(forwards_wave1_backfill, backwards_wave1_backfill),
        migrations.RemoveField(
            model_name='preprocessingorder',
            name='last_ai_import_at',
        ),
    ]
