# Generated by Django 5.2

from django.db import migrations, models


def forwards_receiving_backfill(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    Receiving = apps.get_model('inventory', 'Receiving')
    for po in PurchaseOrder.objects.all().iterator():
        rec = Receiving.objects.filter(purchase_order_id=po.pk).first()
        updates = {}
        if rec and rec.completed_at:
            updates['receiving_status'] = 'done'
            updates['receiving_done_at'] = rec.completed_at
            if rec.created_at:
                updates['receiving_started_at'] = rec.created_at
        elif rec:
            updates['receiving_status'] = 'active'
            if rec.created_at:
                updates['receiving_started_at'] = rec.created_at
        else:
            updates['receiving_status'] = 'not_started'
        if updates:
            PurchaseOrder.objects.filter(pk=po.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_drop_preprocessing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='receiving_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receiving_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='receiving_status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not started'),
                    ('active', 'Active'),
                    ('done', 'Done'),
                ],
                default='not_started',
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards_receiving_backfill, migrations.RunPython.noop),
    ]
