# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def forwards_dispute_backfill(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    Item = apps.get_model('inventory', 'Item')
    Dispute = apps.get_model('inventory', 'Dispute')

    qs = Item.objects.exclude(dispute_type='').exclude(purchase_order_id__isnull=True)
    total = qs.count()
    if total == 0:
        return

    if total > 100:
        # Group by PO + dispute_type; stash item detail in payload
        from collections import defaultdict

        buckets: dict[tuple, list] = defaultdict(list)
        for it in qs.iterator():
            po_id = it.purchase_order_id
            if not po_id:
                continue
            buckets[(po_id, str(it.dispute_type or ''))].append({
                'item_id': it.id,
                'sku': getattr(it, 'sku', '') or '',
                'dispute_pct_loss': it.dispute_pct_loss,
                'dispute_description': it.dispute_description or '',
                'status': it.status,
            })
        for (po_id, dtype), payload_items in buckets.items():
            title = f'Processing dispute ({dtype}) - {len(payload_items)} items'
            Dispute.objects.create(
                purchase_order_id=po_id,
                kind='processing',
                status='open',
                title=title[:300],
                description='Migrated from item-level dispute fields (grouped backfill).',
                opened_at=timezone.now(),
                payload={'items': payload_items, 'dispute_type': dtype, 'grouped': True},
            )
        affected = {po_id for (po_id, _t) in buckets}
    else:
        affected = set()
        for it in qs.iterator():
            po_id = it.purchase_order_id
            if not po_id:
                continue
            affected.add(po_id)
            title = f'Processing dispute ({it.dispute_type}) - {getattr(it, "sku", "")}'
            Dispute.objects.create(
                purchase_order_id=po_id,
                kind='processing',
                status='open',
                title=title[:300],
                description=str(it.dispute_description or ''),
                opened_at=timezone.now(),
                subject_item_id=it.id,
                payload={
                    'dispute_type': it.dispute_type,
                    'dispute_pct_loss': it.dispute_pct_loss,
                    'source': 'item_backfill',
                },
            )

    for po_id in affected:
        open_ct = Dispute.objects.filter(
            purchase_order_id=po_id,
            kind='processing',
            status='open',
        ).count()
        if open_ct:
            PurchaseOrder.objects.filter(pk=po_id).update(processing_dispute_status='active')
        else:
            has_any = Dispute.objects.filter(purchase_order_id=po_id, kind='processing').exists()
            PurchaseOrder.objects.filter(pk=po_id).update(
                processing_dispute_status='resolved' if has_any else 'none',
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0048_receiving_track_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('intake', 'Intake'), ('processing', 'Processing')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='inventory.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('subject_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='inventory.item')),
                ('subject_manifest_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='inventory.manifestrow')),
                ('subject_processing_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='inventory.processingrow')),
                ('subject_pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='inventory.receivingpallet')),
                ('subject_receiving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='inventory.receiving')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['purchase_order', 'kind', 'status'], name='inventory_d_purchas_2f1e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['kind', 'status'], name='inventory_d_kind_0bc5c4_idx'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='intake_dispute_status',
            field=models.CharField(
                choices=[('none', 'None'), ('active', 'Active'), ('resolved', 'Resolved')],
                default='none',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='processing_dispute_status',
            field=models.CharField(
                choices=[('none', 'None'), ('active', 'Active'), ('resolved', 'Resolved')],
                default='none',
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards_dispute_backfill, migrations.RunPython.noop),
    ]
