# Generated by Django 5.2

from django.db import migrations, models


def forwards_processing_backfill(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    ProcessingRow = apps.get_model('inventory', 'ProcessingRow')
    ProcessingDataBuild = apps.get_model('inventory', 'ProcessingDataBuild')
    Item = apps.get_model('inventory', 'Item')

    for po in PurchaseOrder.objects.all().iterator():
        prs = ProcessingRow.objects.filter(purchase_order_id=po.pk)
        total_bm = prs.count()
        linked_bm = prs.exclude(manifest_row_id__isnull=True).count()

        has_items = Item.objects.filter(purchase_order_id=po.pk).exists()
        uses_legacy = bool(has_items and linked_bm == 0)

        build = ProcessingDataBuild.objects.filter(purchase_order_id=po.pk).first()
        proc_status = 'not_started'
        started_at = None
        done_at = None

        if build:
            started_at = build.started_at
            done_at = build.completed_at

        if build and build.status == 'complete':
            proc_status = 'done'
        elif build and build.status in ('running', 'pending', 'failed', 'blocked'):
            if linked_bm and linked_bm == total_bm and total_bm > 0:
                proc_status = 'done'
            else:
                proc_status = 'active'
        elif total_bm > 0 and linked_bm == total_bm and has_items:
            proc_status = 'done'
        elif total_bm > 0 and linked_bm > 0:
            proc_status = 'active'

        updates = {
            'uses_legacy_processing': uses_legacy,
            'processing_status': proc_status,
            'processing_started_at': started_at,
            'processing_done_at': done_at if proc_status == 'done' else None,
        }
        PurchaseOrder.objects.filter(pk=po.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_dispute_model_and_rollups'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='processing_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='uses_legacy_processing',
            field=models.BooleanField(
                default=False,
                help_text='When True, legacy deliver/check-in paths may apply. New intake POs use Processing for ManifestRow/Item materialization.',
            ),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='processing_status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not started'),
                    ('active', 'Active'),
                    ('done', 'Done'),
                ],
                default='not_started',
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards_processing_backfill, migrations.RunPython.noop),
    ]
