# Generated by Django 5.2 on 2026-05-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_processing_track_and_legacy_flag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispute',
            new_name='inventory_d_purchas_c3911a_idx',
            old_name='inventory_d_purchas_2f1e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='dispute',
            new_name='inventory_d_kind_360bea_idx',
            old_name='inventory_d_kind_0bc5c4_idx',
        ),
    ]
