# Generated by Django 5.2 on 2026-05-19 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_rename_inventory_d_purchas_2f1e4c_idx_inventory_d_purchas_c3911a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['purchase_order', 'status'], name='inventory_i_purchas_85f422_idx'),
        ),
    ]
