# Generated by Django 5.2 on 2026-06-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_processingcheckinbatch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processingcheckinbatch',
            new_name='inventory_p_purchas_12fed9_idx',
            old_name='inventory_purchas_754ba4_idx',
        ),
        migrations.RenameIndex(
            model_name='processingcheckinbatch',
            new_name='inventory_p_process_9b581c_idx',
            old_name='inventory_process_7d792e_idx',
        ),
        migrations.RenameIndex(
            model_name='processingrow',
            new_name='inventory_p_purchas_47bcdb_idx',
            old_name='inv_proc_po_row_kind_idx',
        ),
        migrations.AddField(
            model_name='preprocessingrow',
            name='final_matched_product',
            field=models.ForeignKey(blank=True, help_text='Decided product match for this line; null = believed new product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='preprocessingrow',
            name='match_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Scored product suggestions: [{product_id, score, source: upc|vendor_ref|text, snapshot: {title, brand, upc, default_price, product_number}}]. Staging-only.'),
        ),
        migrations.AddField(
            model_name='preprocessingrow',
            name='match_source',
            field=models.CharField(blank=True, choices=[('', 'Undecided'), ('auto', 'Auto (matcher)'), ('staff', 'Staff')], default='', help_text='Who decided final_matched_product; staff decisions are never auto-overridden.', max_length=8),
        ),
    ]
