# Generated by Django 5.2 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_preprocessing_match_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrow',
            name='distinct_product_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Count of distinct Item.product_id among dispositioned items for this row (P4 split).',
            ),
        ),
    ]
