# Generated by Django 5.2 on 2026-06-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_processingrow_collapse_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_count',
            field=models.PositiveIntegerField(default=1, help_text='Physical units contained in this sellable Item (a "set of 10" tag = 10). One physical unit lives in exactly one active Item; unit reports sum this field.'),
        ),
        migrations.AddField(
            model_name='processingrow',
            name='original_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Root row fields captured before the first transform; Restart row restores from this.'),
        ),
        migrations.AddField(
            model_name='processingrow',
            name='split_parent',
            field=models.ForeignKey(blank=True, help_text="P9 transforms: set on SUB rows created by Break apart / Make set. Sub rows share the parent's manifest_row; the manifest line itself is never split.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_children', to='inventory.processingrow'),
        ),
        migrations.AddField(
            model_name='processingrow',
            name='split_seq',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Display ordinal for sub rows: parent #12 shows children as #12.1, #12.2 …', null=True),
        ),
        migrations.AddField(
            model_name='processingrow',
            name='transforms',
            field=models.JSONField(blank=True, default=list, help_text='Audit list of Break apart / Make set operations applied to this ROOT row: [{op, units, factor|set_size, in_place, sub_row_id, created_product_id, by, at}].'),
        ),
        migrations.AddField(
            model_name='processingrow',
            name='units_per_item',
            field=models.PositiveIntegerField(default=1, help_text='Physical units inside each Item checked in from this row (Make set rows: set size; Break apart leftovers: known pack size). Stamped onto Item.unit_count.'),
        ),
    ]
