# Generated by Django 5.2 on 2026-06-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_remove_itemcheckin_item_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_item_check_in_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcheckin',
            new_name='inventory_i_purchas_396ee5_idx',
            old_name='inventory_p_purchas_12fed9_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcheckin',
            new_name='inventory_i_process_ce9f96_idx',
            old_name='inventory_p_process_9b581c_idx',
        ),
        migrations.RenameIndex(
            model_name='itemcheckin',
            new_name='inventory_i_purchas_459c61_idx',
            old_name='inventory_purchas_mrow_idx',
        ),
    ]
