# Generated by Django 5.2 on 2026-06-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_item_label_printed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('bench', 'Bench'), ('executing', 'Executing'), ('done', 'Done')], db_index=True, default='queued', max_length=20)),
                ('scale', models.CharField(blank=True, default='', max_length=64)),
                ('grade_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('item_check_in', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='restoration_job', to='inventory.itemcheckin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration_jobs', to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restoration_jobs', to='inventory.purchaseorder')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['stage', 'updated_at'], name='inventory_r_stage_a56666_idx')],
            },
        ),
    ]
