# Generated by Cursor on 2026-06-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_restoration_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationjob',
            name='return_disposition_type',
            field=models.CharField(
                blank=True,
                choices=[('tars_completed', 'TARS completed'), ('untouched', 'Untouched')],
                default='',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='return_grade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='return_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='return_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='return_scale',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='returned_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='restoration_jobs_returned',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='restorationjob',
            name='stage',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued'),
                    ('sent', 'Sent'),
                    ('bench', 'Bench'),
                    ('executing', 'Executing'),
                    ('done', 'Done'),
                    ('returned', 'Returned to Processing'),
                ],
                db_index=True,
                default='queued',
                max_length=20,
            ),
        ),
    ]
