# Generated by Django 5.2 on 2026-06-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SEED_SCALES = [
    ('Functional', ['Working', 'Repairable', 'Parts-only'], 10),
    ('Completeness', ['Complete', 'Incomplete'], 20),
    ('Assembly', ['Assembled', 'Flat-pack', 'Parts'], 30),
    ('Condition', ['New', 'Like-new', 'Good', 'Fair', 'Salvage'], 40),
]


def seed_restoration_grade_scales(apps, schema_editor):
    RestorationGradeScale = apps.get_model('inventory', 'RestorationGradeScale')
    for name, grades, sort_order in SEED_SCALES:
        RestorationGradeScale.objects.get_or_create(
            name=name,
            defaults={'grades': grades, 'sort_order': sort_order, 'is_active': True},
        )


def unseed_restoration_grade_scales(apps, schema_editor):
    RestorationGradeScale = apps.get_model('inventory', 'RestorationGradeScale')
    RestorationGradeScale.objects.filter(name__in=[row[0] for row in SEED_SCALES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_restoration_return_disposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationGradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('grades', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_grade_scales_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_restoration_grade_scales, unseed_restoration_grade_scales),
    ]
