# Generated by Django 5.2 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_restoration_grade_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationjob',
            name='work_session',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
