# Generated by Django 5.2 on 2026-06-24 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_restoration_job_work_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationPartsRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('url', models.URLField(blank=True, default='')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ordered', 'Ordered'), ('received', 'Received'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('linked_grade', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='bench_disposition',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('storage', 'Storage'), ('salvage', 'Salvage'), ('online_sales', 'Online Sales')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='bench_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='disposition_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='dispositioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='dispositioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_jobs_dispositioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='final_grade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='spent_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='spent_parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='timer_is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='waiting_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='waiting_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='waiting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='waiting_storage_location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='restorationjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('bench', 'Bench'), ('waiting', 'Waiting'), ('executing', 'Executing'), ('done', 'Done'), ('returned', 'Returned to Processing')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='RestorationPartsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('selected_grade', models.CharField(blank=True, default='', max_length=64)),
                ('eval_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_requests', to='inventory.restorationjob')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_parts_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RestorationPartsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=128)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.restorationpartsrequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RestorationPartsOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.restorationpartsorder')),
                ('request_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='inventory.restorationpartsrequestline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RestorationPartsRequestSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='inventory.restorationpartsrequest')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restorationpartsrequestline',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.restorationpartsrequestsite'),
        ),
        migrations.AddField(
            model_name='restorationpartsorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.restorationpartsrequestsite'),
        ),
        migrations.AddIndex(
            model_name='restorationpartsrequest',
            index=models.Index(fields=['status', 'updated_at'], name='inventory_r_status_309f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationpartsrequest',
            index=models.Index(fields=['job', 'status'], name='inventory_r_job_id_ba1454_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationpartsorder',
            index=models.Index(fields=['status', 'expected_delivery'], name='inventory_r_status_cfeacd_idx'),
        ),
    ]
