# Generated by Django 5.2 on 2026-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_itemhistory_dashboard_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationpartsorder',
            name='supplier_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
