# Generated by Django 5.2 on 2026-07-01 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_restorationjob_processing_handled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('bench', 'Bench'), ('pending', 'Pending'), ('done', 'Done'), ('returned', 'Returned to Processing')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='restorationjob',
            index=models.Index(condition=models.Q(('processing_handled_at__isnull', True)), fields=['dispositioned_at'], name='restjob_disp_unhandled_idx'),
        ),
    ]
