# Generated by Django 5.2 on 2026-07-03 20:49

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0078_alter_restorationjob_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm must exist before the gin_trgm_ops indexes below can be created.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-checked_in_at', '-created_at'], name='item_checkedin_created_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='item_searchtext_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='po_searchtext_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
