# Generated by Django 5.2 on 2026-07-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_item_item_checkedin_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationjob',
            name='valuation_fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='valuation_request_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='valuation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='valuation_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_jobs_valuation_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='valuation_requested_grades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='restorationjob',
            index=models.Index(condition=models.Q(('valuation_fulfilled_at__isnull', True), ('valuation_requested_at__isnull', False)), fields=['valuation_requested_at'], name='restjob_valuation_pending_idx'),
        ),
    ]
