# Generated by Django 5.2 on 2026-07-13 21:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def backfill_tars_studio(apps, schema_editor):
    RestorationJob = apps.get_model('inventory', 'RestorationJob')
    RestorationTimelineEvent = apps.get_model('inventory', 'RestorationTimelineEvent')

    unique_owner_ids = set(
        RestorationJob.objects.filter(
            stage='bench',
            timer_started_by_id__isnull=False,
        )
        .values('timer_started_by_id')
        .annotate(job_count=Count('id'))
        .filter(job_count=1)
        .values_list('timer_started_by_id', flat=True)
    )
    if unique_owner_ids:
        for job in RestorationJob.objects.filter(
            stage='bench',
            timer_started_by_id__in=unique_owner_ids,
        ).iterator():
            job.bench_owner_id = job.timer_started_by_id
            job.save(update_fields=['bench_owner'])

    for job in RestorationJob.objects.all().iterator():
        RestorationTimelineEvent.objects.create(
            job_id=job.pk,
            event_type='legacy.snapshot',
            entity_id=f'job:{job.pk}',
            occurred_at=job.updated_at or job.created_at,
            actor_id=job.created_by_id,
            payload={
                'stage': job.stage,
                'scale': job.scale,
                'grade_values': job.grade_values or {},
                'work_session': job.work_session or {},
                'note': 'Current state imported when the TARS Studio timeline was introduced.',
            },
        )


def reverse_tars_studio_backfill(apps, schema_editor):
    RestorationJob = apps.get_model('inventory', 'RestorationJob')
    RestorationTimelineEvent = apps.get_model('inventory', 'RestorationTimelineEvent')
    RestorationTimelineEvent.objects.filter(event_type='legacy.snapshot').delete()
    RestorationJob.objects.update(bench_owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0080_restoration_valuation_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revised', 'Revised'), ('voided', 'Voided')], default='active', max_length=16)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='bench_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_jobs_on_bench', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='last_meaningful_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='last_meaningful_action_label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='last_meaningful_active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restorationtimelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorationtimelineevent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='inventory.restorationjob'),
        ),
        migrations.AddField(
            model_name='restorationtimelineevent',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='inventory.restorationtimelineevent'),
        ),
        migrations.AddField(
            model_name='restorationtimelineevent',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_timeline_events_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_tars_studio, reverse_tars_studio_backfill),
        migrations.AddConstraint(
            model_name='restorationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('bench_owner__isnull', False), ('stage', 'bench')), fields=('bench_owner',), name='restjob_one_bench_per_owner'),
        ),
        migrations.AddIndex(
            model_name='restorationtimelineevent',
            index=models.Index(fields=['job', 'occurred_at', 'id'], name='rest_event_job_time_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationtimelineevent',
            index=models.Index(fields=['job', 'event_type', 'status'], name='rest_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='restorationtimelineevent',
            index=models.Index(fields=['correlation_id'], name='rest_event_corr_idx'),
        ),
    ]
