# Generated by Django 5.2 on 2026-07-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0081_tars_studio_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingattachment',
            name='thumbnail_file',
            field=models.ForeignKey(blank=True, help_text='480px JPEG thumbnail for grid UI; s3_file remains the 2048px high-res.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_attachment_thumbnails', to='core.s3file'),
        ),
        migrations.CreateModel(
            name='ReceivingPhotoOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bol', 'BOL'), ('truck', 'Truck'), ('pallet_side', 'Pallet Side')], max_length=20)),
                ('pallet_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('front', 'Front'), ('right', 'Right'), ('back', 'Back'), ('left', 'Left')], default='', max_length=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_photo_overrides', to=settings.AUTH_USER_MODEL)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_overrides', to='inventory.receiving')),
            ],
            options={
                'indexes': [models.Index(fields=['receiving', 'kind'], name='inventory_r_receivi_537360_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ('bol', 'truck'))), fields=('receiving', 'kind'), name='uniq_receiving_photo_override_bol_truck'), models.UniqueConstraint(condition=models.Q(('kind', 'pallet_side')), fields=('receiving', 'kind', 'pallet_number', 'side'), name='uniq_receiving_photo_override_pallet_side')],
            },
        ),
    ]
