# Generated by Django 5.2 on 2026-08-12 17:59

from django.db import migrations, models


def seed_look_seconds(apps, schema_editor):
    """Give historical time a bucket so look + work still equals the total.

    We cannot know how past bench time split between investigating and working,
    and inventing a split would put numbers in the record that nobody measured.
    Counting it all as time on the item is the honest option: reported hours
    stay correct, and no minute is falsely credited to a grade.
    """

    RestorationJob = apps.get_model('inventory', 'RestorationJob')
    RestorationJob.objects.filter(active_seconds__gt=0).update(
        look_seconds=models.F('active_seconds'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_receiving_photo_thumbnails_and_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationjob',
            name='look_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='starting_grade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='timer_grade',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='timer_mode',
            field=models.CharField(choices=[('look', 'Looking at the item'), ('work', 'Working toward a grade')], default='look', max_length=8),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='value_added',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='work_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_look_seconds, migrations.RunPython.noop),
    ]
