# Generated by Django 5.2 on 2026-08-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_restorationjob_look_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationjob',
            name='intended_destination',
            field=models.CharField(blank=True, choices=[('shelf', 'Shelf'), ('online_sales', 'Online Sales'), ('storage', 'Storage'), ('staff_pick', 'Staff Pick')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='queue_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
