# Generated by Django 5.2 on 2026-08-12 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_restorationjob_intended_destination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(choices=[('inspect', 'Inspect'), ('test', 'Test'), ('repair', 'Repair'), ('assemble', 'Assemble'), ('salvage', 'Salvage')], default='inspect', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restoration_actions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='inventory.restorationjob')),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restorationjob',
            name='current_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.restorationaction'),
        ),
        migrations.AddIndex(
            model_name='restorationaction',
            index=models.Index(fields=['job', 'started_at'], name='inventory_r_job_id_0c7920_idx'),
        ),
    ]
