# Generated by Django 5.2 on 2026-09-24 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_parts_order_line_inspect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='normalize_brand() of the spelling.', max_length=200, unique=True)),
                ('brand', models.CharField(blank=True, default='', help_text='Canonical name; blank when junk.', max_length=200)),
                ('is_junk', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', help_text='e.g. R-023 cluster, human.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', max_length=40)),
                ('display_title', models.CharField(blank=True, default='', max_length=120)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('key_specs', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('retail_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_band', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('search_keywords', models.JSONField(blank=True, default=list)),
                ('dup_group', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('field_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_profiles', to='inventory.product')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('value', models.JSONField()),
                ('source', models.CharField(help_text='copy | rule | vector | ai:<model> | human', max_length=80)),
                ('confidence', models.CharField(blank=True, default='', max_length=10)),
                ('second_opinion', models.JSONField(blank=True, default=dict)),
                ('dollars', models.DecimalField(decimal_places=2, default=0, help_text='Sold dollars behind this product.', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Needs review'), ('auto', 'Auto-accepted, not yet applied'), ('accepted', 'Accepted by a person, not yet applied'), ('rejected', 'Rejected'), ('applied', 'Applied to the profile')], db_index=True, default='pending', max_length=10)),
                ('batch', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('rules_version', models.CharField(blank=True, default='', max_length=80)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_proposals', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='inventory.product')),
            ],
            options={
                'ordering': ['-dollars', 'id'],
                'indexes': [models.Index(fields=['status', '-dollars'], name='inv_proposal_status_dollars'), models.Index(fields=['product', 'field'], name='inv_proposal_product_field')],
            },
        ),
    ]
