# Generated by Django 5.2 on 2026-09-24 13:29
"""Trigram index on Product.title for near-duplicate search (product_intelligence Phase 4, R-022).

Built CONCURRENTLY so the release-phase migrate never locks inventory_product for writes
(check-in and POS keep working while it builds). pg_trgm is installed by inventory/0079.
"""

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('inventory', '0097_product_profile_brand_alias_proposal'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='inv_product_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
