"""Product embeddings in pgvector (product_intelligence Phase 2, step 6). Creates the extension."""
# Generated by Django 5.2 on 2026-09-24 14:30

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    """
    Create pgvector in the connection's own schema (ecothrift in dev and prod, public in test
    databases), then make sure the ``vector`` type is visible to this connection. If pgvector
    lives in a schema outside search_path (e.g. created by hand in ``public``), stop with a
    clear message before any table is created.
    """
    with schema_editor.connection.cursor() as c:
        c.execute('SELECT current_schema()')
        schema = c.fetchone()[0]
        c.execute("SELECT n.nspname FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace WHERE e.extname = 'vector'")
        row = c.fetchone()
        if row is None:
            c.execute(f'CREATE EXTENSION IF NOT EXISTS vector SCHEMA "{schema}"')
        c.execute("SELECT to_regtype('vector') IS NOT NULL")
        if not c.fetchone()[0]:
            raise RuntimeError(
                f'pgvector is installed in schema {row[0] if row else "?"} but this connection searches {schema}. '
                f'Run: ALTER EXTENSION vector SET SCHEMA {schema};'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_product_title_trgm'),
    ]

    operations = [
        # pgvector 0.8.1: preinstalled on Heroku; built locally for PostgreSQL 18 (owner, 2026-09-24).
        migrations.RunPython(create_vector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProductVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('text_hash', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='inventory.product')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='inv_productvector_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('product', 'model_name'), name='inv_productvector_product_model_uniq')],
            },
        ),
    ]
