# Generated by Django 5.2 on 2026-09-24 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_product_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('moved', models.JSONField(default=dict)),
                ('merged_was_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_merges', to=settings.AUTH_USER_MODEL)),
                ('merged', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_as_merged', to='inventory.product')),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_as_survivor', to='inventory.product')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_merges_undone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merged', 'undone_at'], name='inv_catalogmerge_merged_live')],
            },
        ),
    ]
