# Generated by Django 5.2 on 2026-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_catalog_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='vector_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
