# Generated by Django 5.2 on 2026-09-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_profile_vector_text_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedupeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('same', 'Same product'), ('different', 'Different products')], max_length=10)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(help_text='ai:<model> | human', max_length=80)),
                ('rules_version', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.catalogmerge')),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product_a', 'product_b', 'rules_version'), name='dedupe_pair_per_version')],
            },
        ),
    ]
