# Generated by Django 5.2 on 2026-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_drop_template_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscanhistory',
            name='outcome',
            field=models.CharField(choices=[('added_to_cart', 'Added to cart'), ('pos_blocked_sold', 'POS blocked (already sold)'), ('pos_sold_tag_moved', 'POS: sold tag in hand, old sale moved to a new item'), ('public_lookup', 'Public lookup'), ('audit_scan', 'Audit scan')], default='added_to_cart', max_length=30),
        ),
    ]
