# Generated by Django 5.2 on 2026-06-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_timeentrymodificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='on_break',
            field=models.BooleanField(default=False),
        ),
    ]
