# Generated by Django 5.2 on 2026-09-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_catalog_merge'),
        ('thriftplus', '0002_seed_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReward',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thrift_reward', serialize=False, to='inventory.item')),
                ('family_key', models.CharField(db_index=True, help_text='f<family id>, or p<product id> for a product alone.', max_length=24)),
                ('floor_date', models.DateField(help_text='The day the item reached the floor (day 1 before the program start setting).')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_price', models.DecimalField(decimal_places=2, help_text='A member never pays less: the floor share of the tag.', max_digits=10)),
                ('grow_days', models.PositiveSmallIntegerField(default=0, help_text='Days the reward has grown (price / 90 each).')),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'Days 1 to 7'), ('climbing', 'Climbing'), ('paused', 'Held: family selling on pace'), ('capped', 'At the floor'), ('no_room', 'No tag price'), ('excluded', 'Excluded'), ('closed', 'Off the floor')], db_index=True, default='waiting', max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=40)),
                ('day', models.SmallIntegerField(default=0, help_text='The day number at the last recompute.')),
                ('computed_on', models.DateField(db_index=True)),
                ('exit_on', models.DateField(blank=True, db_index=True, help_text='The day it reached day 90: on the exit list.', null=True)),
                ('scans', models.PositiveIntegerField(default=0)),
                ('adds', models.PositiveIntegerField(default=0)),
                ('passes', models.PositiveIntegerField(default=0)),
                ('feedback', models.JSONField(blank=True, default=dict, help_text='"Price feel off?" chip counts.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_status', models.CharField(blank=True, default='', help_text="The item's status when it left the floor.", max_length=20)),
                ('reward_at_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reward'],
            },
        ),
        migrations.CreateModel(
            name='RewardFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, help_text='The day the rewards apply to.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reward_family_link', serialize=False, to='inventory.product')),
                ('source', models.CharField(choices=[('asked', 'Asked the model'), ('neighbour', "Named in a neighbour's answer"), ('alone', 'No close neighbours on the floor')], max_length=10)),
                ('answer', models.JSONField(blank=True, default=dict, help_text='The neighbours considered and what the model said.')),
                ('model_used', models.CharField(blank=True, default='', max_length=80)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='thriftplus.rewardfamily')),
            ],
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateField()),
                ('day', models.SmallIntegerField()),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='thriftplus.itemreward')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='thriftplus.rewardrun')),
            ],
            options={
                'ordering': ['-on', '-pk'],
                'indexes': [models.Index(fields=['item_reward', 'on'], name='thriftplus__item_re_3b92dd_idx')],
            },
        ),
    ]
