# Generated by Django 5.2 on 2026-09-25 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_catalog_merge'),
        ('pos', '0033_thrift_plus_fields'),
        ('thriftplus', '0004_seed_reward_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMember',
            fields=[
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thrift_member', serialize=False, to='pos.cart')),
                ('reward_choice', models.CharField(choices=[('instant', 'Instant rebate'), ('bank', 'Bank my rewards')], default='instant', max_length=10)),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, help_text='Store credit spent on this sale.', max_digits=10)),
                ('bank_used', models.DecimalField(decimal_places=2, default=0, help_text='Banked rewards spent on this sale.', max_digits=10)),
                ('rering', models.BooleanField(default=False, help_text='Attached after the sale was completed (re-ring as a member).')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='thriftplus.account')),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='thriftplus.card')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='thriftplus.person')),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thrift_restriction', serialize=False, to='inventory.product')),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cover', 'Monthly cover'), ('bank', 'Banked rewards'), ('credit', 'Store credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: + adds to the balance or cover, - takes away.', max_digits=10)),
                ('month', models.CharField(blank=True, default='', help_text='YYYY-MM, for the cover.', max_length=7)),
                ('reason', models.CharField(help_text='sale, void, return, rering, spend, adjust.', max_length=20)),
                ('cart_line_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='thriftplus.account')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thrift_ledger', to='pos.cart')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.item')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='thriftplus.ledgerentry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['account', 'kind', 'month'], name='thriftplus__account_792dcf_idx')],
            },
        ),
    ]
