# Generated by Django 5.2 on 2026-09-25 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_catalog_merge'),
        ('pos', '0033_thrift_plus_fields'),
        ('thriftplus', '0006_seed_register_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, help_text='The store credit given: 95% of what was paid for the line, before tax.', max_digits=10)),
                ('note', models.TextField(blank=True, default='', help_text="What doesn't work.")),
                ('status', models.CharField(choices=[('open', 'Waiting for staff'), ('done', 'Handled')], default='open', help_text='Staff decide what happens to the item.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='thriftplus.account')),
                ('cart_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='thrift_return', to='pos.cartline')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='thriftplus.person')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='thriftplus/sale_photos/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('cart_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thrift_photos', to='pos.cartline')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
