# Generated by Django 5.2 on 2026-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thriftplus', '0010_staff_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Lower-cased. Where receipts and the updates they asked for go (email-first, T73).', max_length=254),
        ),
    ]
