# Generated by Django 5.2 on 2026-04-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(blank=True, default='', max_length=300)),
                ('condition_summary', models.CharField(blank=True, default='', max_length=500)),
                ('lot_size', models.PositiveIntegerField(blank=True, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bid_count', models.PositiveIntegerField(blank=True, null=True)),
                ('time_remaining_seconds', models.IntegerField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closing', 'Closing'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('has_manifest', models.BooleanField(default=False)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ai_score_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('strategy', models.CharField(choices=[('early_max', 'Early max'), ('incremental', 'Incremental'), ('snipe', 'Snipe'), ('other', 'Other')], default='other', max_length=20)),
                ('bid_time', models.DateTimeField()),
                ('was_winning', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='buying.auction')),
            ],
            options={
                'ordering': ['-bid_time'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='buying.marketplace'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hammer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('win', models.BooleanField(default=False)),
                ('margin_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='buying.auction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('bidding', 'Bidding'), ('won', 'Won'), ('lost', 'Lost'), ('passed', 'Passed')], db_index=True, default='watching', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=60)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entry', to='buying.auction')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bid_count', models.PositiveIntegerField(blank=True, null=True)),
                ('time_remaining_seconds', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='buying.auction')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['auction', 'captured_at'], name='buying_auct_auction_3464f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManifestRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('brand', models.CharField(blank=True, default='', max_length=300)),
                ('model', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(blank=True, default='', max_length=300)),
                ('sku', models.CharField(blank=True, default='', max_length=200)),
                ('upc', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('retail_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_rows', to='buying.auction')),
            ],
            options={
                'ordering': ['auction', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('auction', 'row_number'), name='buying_manifestrow_auction_row_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['marketplace', 'status'], name='buying_auct_marketp_7322ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='auction',
            constraint=models.UniqueConstraint(fields=('marketplace', 'external_id'), name='buying_auction_marketplace_external_id_uniq'),
        ),
    ]
