# Generated by Django 5.2 on 2026-04-07 19:32

from django.db import migrations, models


def seed_bstock_marketplaces(apps, schema_editor):
    Marketplace = apps.get_model('buying', 'Marketplace')
    seed = [
        ('Target', 'target', '681ba6075fcfe8a77834e039', 'https://bstock.com/buy/seller/target'),
        ('Walmart', 'walmart', '66562833b29d4ed2184fb048', 'https://bstock.com/buy/seller/walmart'),
        ('Costco', 'costco', '671006ab361622722de6a918', 'https://bstock.com/buy/seller/costco'),
        ('Amazon', 'amazon', '6890f7d62ed3f874681ba620', 'https://bstock.com/buy/seller/amazon'),
        ('Home Depot', 'homedepot', '6881261faf84045af78617c9', 'https://bstock.com/buy/seller/homedepot'),
        ('Wayfair', 'wayfair', '69b09e3a59abd904a59f5459', 'https://bstock.com/buy/seller/wayfair'),
    ]
    for name, slug, storefront_id, base_url in seed:
        Marketplace.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'external_id': storefront_id,
                'base_url': base_url,
                'is_active': True,
            },
        )


def unseed_bstock_marketplaces(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_ext_id',
            field=models.CharField(blank=True, help_text='B-Stock auction id from auction service (bids)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='lot_id',
            field=models.CharField(blank=True, db_index=True, help_text='B-Stock lotId (manifests and lot detail)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller_id',
            field=models.CharField(blank=True, help_text='storeFrontId for this listing (reference)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='B-Stock storeFrontId for search API', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='external_id',
            field=models.CharField(db_index=True, help_text='B-Stock listingId (primary listing identifier)', max_length=120),
        ),
        migrations.RunPython(seed_bstock_marketplaces, unseed_bstock_marketplaces),
    ]
