# Generated by Django 5.2 on 2026-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_bstock_ids_and_marketplace_storefront'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, help_text='B-Stock groupId for order-process manifest URL path', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot_id',
            field=models.CharField(blank=True, db_index=True, help_text='B-Stock lotId (e.g. listing.bstock.com groups?lotId=)', max_length=64, null=True),
        ),
    ]
