# Generated by Django 5.2 on 2026-04-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0003_auction_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='listing_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='B-Stock listingType (e.g. SPOT, CONTRACT)', max_length=32),
        ),
        migrations.AddField(
            model_name='auction',
            name='total_retail_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extended retail from search (e.g. retailPrice), dollars', max_digits=14, null=True),
        ),
    ]
