# Generated by Django 5.2 on 2026-04-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0004_auction_listing_type_total_retail'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistentry',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last successful watch poll that updated auction state and wrote a snapshot.', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistentry',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Minimum seconds between successful polls for this row (scheduler cadence should exceed this).'),
        ),
    ]
