# Generated by Django 5.2 on 2026-04-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0005_watchlist_poll_interval_last_polled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, help_text='Normalized key: strip() only; case preserved (matches ManifestRow.category.strip()).', max_length=400, unique=True)),
                ('canonical_category', models.CharField(choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], max_length=64)),
                ('rule_origin', models.CharField(choices=[('seeded', 'Seeded'), ('ai', 'AI'), ('manual', 'Manual')], max_length=16)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_key'],
            },
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='canonical_category',
            field=models.CharField(blank=True, choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='category_confidence',
            field=models.CharField(blank=True, choices=[('direct', 'Direct match'), ('ai_mapped', 'AI mapped'), ('fallback', 'Auction fallback')], max_length=16, null=True),
        ),
    ]
