# Generated by Django 5.2 on 2026-04-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0006_category_mapping_and_manifest_canonical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestrow',
            name='category',
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='fast_cat_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='fast_cat_value',
            field=models.CharField(blank=True, choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='source_key',
            field=models.CharField(db_index=True, help_text='Lookup key: typically ManifestRow.fast_cat_key (vendor-prefixed slug).', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='manifestrow',
            name='category_confidence',
            field=models.CharField(blank=True, choices=[('direct', 'Direct match'), ('ai_mapped', 'AI mapped'), ('fallback', 'Auction fallback'), ('fast_cat', 'Fast category (manifest template)')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='ManifestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_signature', models.CharField(db_index=True, max_length=2000)),
                ('display_name', models.CharField(max_length=200)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('category_fields', models.JSONField(blank=True, default=list)),
                ('category_field_transforms', models.JSONField(blank=True, default=dict)),
                ('min_fill_threshold', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_templates', to='buying.marketplace')),
            ],
            options={
                'ordering': ['marketplace', 'header_signature'],
            },
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='manifest_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_rows', to='buying.manifesttemplate'),
        ),
        migrations.AddConstraint(
            model_name='manifesttemplate',
            constraint=models.UniqueConstraint(fields=('marketplace', 'header_signature'), name='buying_manifesttemplate_marketplace_header_uniq'),
        ),
    ]
