# Generated by Django 5.2 on 2026-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0007_manifest_template_and_fast_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=200, unique=True)),
                ('sell_through_rate', models.DecimalField(decimal_places=4, help_text='Ratio sold/retail (e.g. 0.4448 = 44.48%).', max_digits=6)),
                ('avg_retail', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('version_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sample_size'],
            },
        ),
    ]
