# Generated by Django 5.2 on 2026-04-09 19:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0008_pricing_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ai_category_estimates',
            field=models.JSONField(blank=True, help_text='Tier 1: AI-estimated category mix (% by taxonomy_v1 name).', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='estimated_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected revenue before shrinkage (sumproduct of category mix × sell-through rates).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='estimated_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='estimated_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='manifest_category_distribution',
            field=models.JSONField(blank=True, help_text='Tier 2: distribution from manifest fast_cat_value counts.', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='need_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='1–99; higher surfaces first when auto-ranked.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='priority_override',
            field=models.BooleanField(default=False, help_text='True when priority was set manually and should not be overwritten by auto recompute.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='profit_target_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Override global profit factor (min revenue/cost ratio target).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='profitability_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='revenue_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User override dollar amount; downstream uses coalesce(override, estimated_revenue).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='shrinkage_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Override global shrinkage factor for this auction.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='thumbs_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='default_fee_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Historical avg fee as fraction of purchase price (e.g. 0.03 = 3%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='default_shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Historical avg shipping as fraction of purchase price.', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CategoryWantVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], db_index=True, max_length=64)),
                ('value', models.PositiveSmallIntegerField(help_text='1 = skip, 10 = want; neutral target is 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_want_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='buying_categorywantvote_user_category_uniq')],
            },
        ),
    ]
