# Generated by Django 5.2 on 2026-04-15 00:34

from decimal import Decimal

from django.db import migrations, models

from apps.buying.taxonomy_v1 import TAXONOMY_V1_CATEGORY_NAMES


def seed_category_stats(apps, schema_editor):
    CategoryStats = apps.get_model('buying', 'CategoryStats')
    z = Decimal('0')
    for name in TAXONOMY_V1_CATEGORY_NAMES:
        CategoryStats.objects.update_or_create(
            category=name,
            defaults={
                'sell_through_rate': z,
                'have_retail': z,
                'have_units': 0,
                'want_retail': z,
                'want_units': 0,
                'need_retail': z,
                'need_units': 0,
                'sell_through_numerator': None,
                'sell_through_denominator': None,
            },
        )


def backfill_est_profit(apps, schema_editor):
    Auction = apps.get_model('buying', 'Auction')
    AppSetting = apps.get_model('core', 'AppSetting')
    shrink_global = Decimal('0.10')
    try:
        s = AppSetting.objects.get(key='pricing_shrinkage_factor')
        shrink_global = Decimal(str(s.value))
    except Exception:
        pass
    for a in Auction.objects.all().only(
        'id',
        'estimated_revenue',
        'revenue_override',
        'shrinkage_override',
        'estimated_total_cost',
        'est_profit',
    ).iterator(chunk_size=500):
        if a.estimated_revenue is None and a.revenue_override is None:
            continue
        shr = a.shrinkage_override if a.shrinkage_override is not None else shrink_global
        base = a.revenue_override if a.revenue_override is not None else a.estimated_revenue
        if base is None:
            continue
        eff = (base * (Decimal('1') - shr)).quantize(Decimal('0.01'))
        tc = a.estimated_total_cost
        if tc is None:
            continue
        ep = (eff - tc).quantize(Decimal('0.01'))
        Auction.objects.filter(pk=a.pk).update(est_profit=ep)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0011_auction_thumbs_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=200, unique=True)),
                ('sell_through_rate', models.DecimalField(decimal_places=6, help_text='0–1; 0 when denominator is zero.', max_digits=8)),
                ('have_retail', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('have_units', models.PositiveIntegerField(default=0)),
                ('want_retail', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('want_units', models.PositiveIntegerField(default=0)),
                ('need_retail', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('need_units', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('sell_through_numerator', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sell_through_denominator', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When set, auction is archived (hidden from default lists and sweeps).', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='est_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit after shrink vs total cost (lightweight/full recompute).', max_digits=14, null=True),
        ),
        migrations.RunPython(seed_category_stats, noop_reverse),
        migrations.RunPython(backfill_est_profit, noop_reverse),
    ]
