# Generated by Django 5.2 on 2026-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0012_category_stats_auction_lifecycle_item_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystats',
            name='avg_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mean allocated cost for sold items in the need window (NULL if no costs).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='avg_retail',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mean retail line (retail_value/price) for sold items in the need window.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='avg_sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mean COALESCE(sold_for, price) for sold items in the need window.', max_digits=14, null=True),
        ),
    ]
