# Generated by Django 5.2 on 2026-04-15 21:17

from django.db import migrations, models


def _clamp_need_scores(apps, schema_editor):
    Auction = apps.get_model('buying', 'Auction')
    db_alias = schema_editor.connection.alias
    chunk: list[tuple[int, int]] = []
    for a in Auction.objects.using(db_alias).exclude(need_score__isnull=True).iterator(chunk_size=500):
        raw = a.need_score
        try:
            n = int(round(float(raw)))
        except (TypeError, ValueError):
            n = 50
        n = max(1, min(99, n))
        chunk.append((a.pk, n))
    for pk, n in chunk:
        Auction.objects.using(db_alias).filter(pk=pk).update(need_score=n)


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0013_categorystats_window_avgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystats',
            name='need_score_1to99',
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text='Min–max scaled need vs other taxonomy buckets (1–99); recomputed daily.',
            ),
        ),
        migrations.RunPython(_clamp_need_scores, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auction',
            name='need_score',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='1–99 weighted mix of CategoryStats.need_score_1to99 for this auction.',
                null=True,
            ),
        ),
    ]
