# Generated by Django 5.2 on 2026-04-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0017_categorystats_recovery_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystats',
            name='recovery_rate',
            field=models.DecimalField(decimal_places=6, help_text='0–1; SUM(sold_for)/SUM(retail_value) for qualifying sold rows, all-time; 0 when denominator is zero.', max_digits=8),
        ),
    ]
