# Generated by Django 5.2 — drop legacy global thumbs_up flag (per-user votes live in AuctionThumbsVote).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0019_categorystats_good_data_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='thumbs_up',
        ),
    ]
