# Generated by Django 5.2 on 2026-09-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Keys read by apps.buying.services.buying_settings; Admin -> Assumptions edits them.
MANIFEST_PULL_SETTINGS = [
    ('buying_manifest_pull_window_hours', 36, 'Buying: pull manifests for auctions ending within this many hours (1-168).'),
    ('buying_manifest_pull_max_per_run', 40, 'Buying: most manifests one Pull fetches (at least 1).'),
    ('buying_manifest_pull_retry_hours', 12, 'Buying: wait this long before retrying a failed manifest pull (at least 1).'),
    ('buying_manifest_pull_page_delay_ms', 500, 'Buying: pause between B-Stock manifest requests, in milliseconds.'),
]


def seed_settings_and_backfill_source(apps, schema_editor):
    AppSetting = apps.get_model('core', 'AppSetting')
    for key, value, description in MANIFEST_PULL_SETTINGS:
        AppSetting.objects.get_or_create(key=key, defaults={'value': value, 'description': description})
    Auction = apps.get_model('buying', 'Auction')
    ManifestRow = apps.get_model('buying', 'ManifestRow')
    # Only rows that are clearly a CSV upload (a template, and not the B-Stock API shape with
    # an `_id`) are labelled. Older API pulls and templateless rows stay unlabelled: never
    # shown as "Uploaded CSV", and never pruned as auto pulls.
    api_ids = ManifestRow.objects.filter(raw_data__has_key='_id').values('auction_id')
    csv_ids = ManifestRow.objects.filter(manifest_template__isnull=False).values('auction_id')
    Auction.objects.filter(pk__in=csv_ids).exclude(pk__in=api_ids).update(manifest_source='manual')


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0020_remove_auction_thumbs_up'),
        ('core', '0003_appsettinghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='manifest_pull_attempted_at',
            field=models.DateTimeField(blank=True, help_text='Last auto pull attempt, success or not. The shortlist waits before retrying a failure.', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='manifest_pull_blocked',
            field=models.BooleanField(db_default=False, default=False, help_text='B-Stock will never give this manifest (too large, or none); the pull stops trying.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='manifest_pull_error',
            field=models.CharField(blank=True, db_default='', default='', help_text='Why the last auto pull failed; cleared on success.', max_length=300),
        ),
        migrations.AddField(
            model_name='auction',
            name='manifest_source',
            field=models.CharField(blank=True, choices=[('auto', 'Pulled from B-Stock'), ('manual', 'Uploaded CSV')], db_default='', default='', help_text='Where the current manifest rows came from; blank when there are none.', max_length=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='manifest_pulled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When manifest rows were last saved, by auto pull or CSV upload.', null=True),
        ),
        migrations.CreateModel(
            name='BStockToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestPullJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('stopped', 'Stopped by owner')], default='queued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, help_text='Touched after every page, mapping batch, and auction; a job that goes quiet is picked up again.', null=True)),
                ('runner', models.CharField(blank=True, default='', help_text='Token of the thread or scheduler run that owns the job; a runner that loses it stops.', max_length=32)),
                ('auction_ids', models.JSONField(blank=True, default=list, help_text='The shortlist fixed when the job first ran; a resumed job works through the rest.')),
                ('total', models.PositiveIntegerField(default=0)),
                ('done_count', models.PositiveIntegerField(default=0)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('results', models.JSONField(blank=True, default=list, help_text='[{auction_id, title, ok, rows, error}] in pull order.')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_settings_and_backfill_source, migrations.RunPython.noop),
    ]
