# Generated by Django 5.2 on 2026-09-23 16:32

from decimal import Decimal

from django.db import migrations, models

# B-Stock's buyer fee: 5% of the bid on Target (seen on a listing 2026-09-23); the others are
# assumed 5% until checked. Replaces only an unset rate or the old 3% placeholder.
FEE_RATE = Decimal('0.0500')
OLD_PLACEHOLDER_FEE = Decimal('0.0300')
# Shipping as a share of the price, used only until B-Stock has a quote for the listing.
# Fills blanks only; a rate someone set is kept.
SHIPPING_RATES = {
    'amazon': Decimal('0.3500'),
    'target': Decimal('0.4000'),
    'walmart': Decimal('0.3800'),
    'costco': Decimal('0.3200'),
    'homedepot': Decimal('0.3500'),
    'wayfair': Decimal('0.4200'),
    'essendant': Decimal('0.3000'),
}


def set_marketplace_rates(apps, schema_editor):
    Marketplace = apps.get_model('buying', 'Marketplace')
    for mp in Marketplace.objects.all():
        fields = []
        if mp.default_fee_rate is None or mp.default_fee_rate == OLD_PLACEHOLDER_FEE:
            mp.default_fee_rate = FEE_RATE
            fields.append('default_fee_rate')
        if mp.default_shipping_rate is None and mp.slug in SHIPPING_RATES:
            mp.default_shipping_rate = SHIPPING_RATES[mp.slug]
            fields.append('default_shipping_rate')
        if fields:
            mp.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0021_auction_manifest_auto_pull'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='shipping_quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="B-Stock's freight quote to the buyer's address, in dollars.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping_quote_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was read from B-Stock.', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping_quote_info',
            field=models.JSONField(blank=True, help_text='Carrier, mode (TL / LTL), trucks, destination ZIP, quote id, and B-Stock quote time.', null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='shipping_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional user override for shipping in dollars; else the B-Stock shipping quote; else shipping rate times current price.', max_digits=12, null=True),
        ),
        # Rates only feed valuation; re-value happens on the next sweep / recompute.
        migrations.RunPython(set_marketplace_rates, migrations.RunPython.noop),
    ]
