# Generated by Django 5.2 on 2026-09-23 16:48

import re

from django.db import migrations, models

# Same rule as listing_mapping.pallet_count_from_listing's title fallback.
TITLE_PALLETS_RE = re.compile(r'(\d{1,3})\s+pallets?\b', re.IGNORECASE)

SHIPPING_PER_PALLET = (
    'buying_shipping_per_pallet',
    100,
    'Buying: shipping estimate in $ per pallet for a lot whose city has no B-Stock quotes yet.',
)


def seed_setting_and_backfill_pallets(apps, schema_editor):
    AppSetting = apps.get_model('core', 'AppSetting')
    key, value, description = SHIPPING_PER_PALLET
    AppSetting.objects.get_or_create(key=key, defaults={'value': value, 'description': description})

    # Older auctions: the pallet count from the title. The sweep fills origin and B-Stock's
    # palletCount for live listings on its next run.
    Auction = apps.get_model('buying', 'Auction')
    batch = []
    for pk, title in Auction.objects.filter(pallet_count__isnull=True).values_list('pk', 'title').iterator(
        chunk_size=2000
    ):
        m = TITLE_PALLETS_RE.search(title or '')
        if m and int(m.group(1)) > 0:
            batch.append(Auction(pk=pk, pallet_count=int(m.group(1))))
        if len(batch) >= 1000:
            Auction.objects.bulk_update(batch, ['pallet_count'])
            batch = []
    if batch:
        Auction.objects.bulk_update(batch, ['pallet_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0022_auction_shipping_quote'),
        ('core', '0003_appsettinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='origin_city',
            field=models.CharField(blank=True, db_default='', default='', help_text='Where the lot ships from: B-Stock sellerCity, provinceCode (e.g. "Franklin, IN").', max_length=120),
        ),
        migrations.AddField(
            model_name='auction',
            name='origin_zip',
            field=models.CharField(blank=True, db_default='', default='', max_length=12),
        ),
        migrations.AddField(
            model_name='auction',
            name='pallet_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipment_type',
            field=models.CharField(blank=True, db_default='', default='', help_text='B-Stock shipmentType: Truckload, LTL, or PARCEL.', max_length=20),
        ),
        migrations.RunPython(seed_setting_and_backfill_pallets, migrations.RunPython.noop),
    ]
