# Generated by Django 5.2 on 2026-09-23 17:03

from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify

# Driving miles from the store (8425 West Center Road, Omaha NE 68124), Google Routes,
# 2026-09-23: every city in our purchase-order history. New cities are looked up by the sweep.
CITY_MILES = {
    'Atlanta, GA': 989,
    'Aurora, CO': 534,
    'Dallas, TX': 660,
    'Denver, CO': 532,
    'Franklin, IN': 637,
    'Frederick, MD': 1112,
    'Garland, TX': 665,
    'Gloversville, NY': 1234,
    'Greencastle, PA': 1071,
    'Indianapolis, IN': 616,
    'Katy, TX': 907,
    'Las Vegas, NV': 1278,
    'Mira Loma, CA': 1513,
    'Monroe Township, NJ': 1262,
    'Morris, IL': 428,
    'Owatonna, MN': 319,
    'Plainview, TX': 728,
    'Romeoville, IL': 456,
    'Spartanburg, SC': 1095,
    'Tolleson, AZ': 1304,
    'Tracy, CA': 1639,
    'Twinsburg, OH': 817,
    'Upper Marlboro, MD': 1172,
    'Waco, TX': 741,
    'West Palm Beach, FL': 1586,
}

# Fitted 2026-09-23 on 193 purchase orders and 2 B-Stock quotes (= services/shipping_formula.py DEFAULT_FORMULA).
FORMULA = {
    'truckload': {'fixed': 1667.98, 'per_mile': 1.6709},
    'ltl': {'fixed': 297.78, 'per_pallet': 43.2488, 'per_pallet_mile': 0.07458},
    'truckload_min_pallets': 16,
    'typical_error': {'truckload': 0.25, 'ltl': 0.2},
    'level': {'truckload': 1.62, 'ltl': 1.0},
    'fitted_on': '2026-09-23',
    'rows': 195,
    'cities': 25,
}


def seed(apps, schema_editor):
    ShippingOrigin = apps.get_model('buying', 'ShippingOrigin')
    now = timezone.now()
    for city, miles in CITY_MILES.items():
        ShippingOrigin.objects.get_or_create(
            slug=slugify(city), defaults={'city': city, 'miles': miles, 'looked_up_at': now}
        )
    AppSetting = apps.get_model('core', 'AppSetting')
    AppSetting.objects.get_or_create(
        key='buying_shipping_formula',
        defaults={
            'value': FORMULA,
            'description': (
                'Buying: shipping estimate from distance and pallets. Truckload = fixed + per_mile x miles; '
                'LTL = fixed + per_pallet x pallets + per_pallet_mile x pallets x miles. '
                'Re-fit with: python manage.py fit_shipping_formula --save'
            ),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0023_auction_origin_pallets'),
        ('core', '0003_appsettinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('city', models.CharField(help_text='"City, ST" as B-Stock or a PO names it.', max_length=120)),
                ('miles', models.PositiveIntegerField(blank=True, help_text='Driving miles from the store.', null=True)),
                ('looked_up_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
