# Generated by Django 5.2 on 2026-09-23 17:10

from django.db import migrations, models

# Anonymous B-Stock search returns none of Costco's lots; a signed-in search returned all 272
# (2026-09-23).
SIGNED_IN_ONLY = ['costco']


def mark_signed_in_only(apps, schema_editor):
    Marketplace = apps.get_model('buying', 'Marketplace')
    Marketplace.objects.filter(slug__in=SIGNED_IN_ONLY).update(requires_login=True)


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0024_shipping_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='requires_login',
            field=models.BooleanField(db_default=False, default=False, help_text="B-Stock shows this seller's auctions only to a signed-in buyer (Costco). The sweep searches it with the owner's handed-over login while that login is live."),
        ),
        migrations.RunPython(mark_signed_in_only, migrations.RunPython.noop),
    ]
