# Generated by Django 5.2 on 2026-09-23 17:58

from django.db import migrations, models


def seed_target_weeks(apps, schema_editor):
    AppSetting = apps.get_model('core', 'AppSetting')
    AppSetting.objects.get_or_create(
        key='buying_target_cover_weeks',
        defaults={
            'value': 0,
            'description': (
                "Buying: weeks of stock (shelf + pipeline) to hold per category; 0 = the store's own "
                'average cover. Need v2 is 50 on target.'
            ),
        },
    )
    AppSetting.objects.get_or_create(
        key='buying_pipeline_max_age_days',
        defaults={
            'value': 120,
            'description': 'Buying: open POs older than this are not counted as on order (usually done, never closed).',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0025_marketplace_requires_login'),
        ('core', '0003_appsettinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystats',
            name='cover_weeks',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='(shelf + pipeline) / weekly sales; empty when nothing sold.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='in_building_retail',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='in_building_units',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Items in intake or processing.'),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='median_days_to_sell',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='on_order_retail',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='on_order_units',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Manifest units on open POs with no item yet (ordered to processing).'),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='sold_within_90_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='target_weeks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='categorystats',
            name='weekly_sales_units',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, help_text='Units sold per week over the need window.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='categorystats',
            name='need_score_1to99',
            field=models.PositiveSmallIntegerField(default=50, help_text='Need v2 (1-99): weeks of cover (shelf + pipeline) against the target weeks; 50 = on target, higher = short, lower = overstocked. Recomputed daily.'),
        ),
        migrations.RunPython(seed_target_weeks, migrations.RunPython.noop),
    ]
