# Generated by Django 5.2 on 2026-09-23 21:11

from decimal import Decimal

from django.db import migrations, models
from django.utils.text import slugify

# Added 2026-09-23 (owner): product_intelligence Phase 1, runner R-016.
NEW_CATEGORIES = ('Lawn & garden', 'Appliances', 'Arts & crafts', 'Automotive')


def add_categories(apps, schema_editor):
    CategoryStats = apps.get_model('buying', 'CategoryStats')
    Category = apps.get_model('inventory', 'Category')
    for name in NEW_CATEGORIES:
        CategoryStats.objects.get_or_create(category=name, defaults={'recovery_rate': Decimal('0')})
        Category.objects.get_or_create(name=name, defaults={'slug': slugify(name)})


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0027_priority_profit_weight'),
        ('inventory', '0096_parts_order_line_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='canonical_category',
            field=models.CharField(choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Lawn & garden', 'Lawn & garden'), ('Appliances', 'Appliances'), ('Arts & crafts', 'Arts & crafts'), ('Automotive', 'Automotive'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], max_length=64),
        ),
        migrations.AlterField(
            model_name='manifestrow',
            name='canonical_category',
            field=models.CharField(blank=True, choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Lawn & garden', 'Lawn & garden'), ('Appliances', 'Appliances'), ('Arts & crafts', 'Arts & crafts'), ('Automotive', 'Automotive'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='manifestrow',
            name='fast_cat_value',
            field=models.CharField(blank=True, choices=[('Kitchen & dining', 'Kitchen & dining'), ('Furniture', 'Furniture'), ('Outdoor & patio furniture', 'Outdoor & patio furniture'), ('Home décor & lighting', 'Home décor & lighting'), ('Household & cleaning', 'Household & cleaning'), ('Bedding & bath', 'Bedding & bath'), ('Storage & organization', 'Storage & organization'), ('Toys & games', 'Toys & games'), ('Sports & outdoors', 'Sports & outdoors'), ('Tools & hardware', 'Tools & hardware'), ('Office & school supplies', 'Office & school supplies'), ('Electronics', 'Electronics'), ('Baby & kids', 'Baby & kids'), ('Health, beauty & personal care', 'Health, beauty & personal care'), ('Apparel & accessories', 'Apparel & accessories'), ('Books & media', 'Books & media'), ('Pet supplies', 'Pet supplies'), ('Party, seasonal & novelty', 'Party, seasonal & novelty'), ('Lawn & garden', 'Lawn & garden'), ('Appliances', 'Appliances'), ('Arts & crafts', 'Arts & crafts'), ('Automotive', 'Automotive'), ('Mixed lots & uncategorized', 'Mixed lots & uncategorized')], max_length=64, null=True),
        ),
        migrations.RunPython(add_categories, migrations.RunPython.noop),
    ]
