# Generated by Django 5.2 on 2026-09-23 22:09

from django.db import migrations, models


def seed_speed_weight(apps, schema_editor):
    AppSetting = apps.get_model('core', 'AppSetting')
    AppSetting.objects.get_or_create(
        key='buying_priority_speed_weight',
        defaults={
            'value': 0,
            'description': (
                "Buying: sell speed's share of auction Priority (0-1). Speed = the auction's category mix x "
                '30-day sell-through. 0 = Priority ignores speed.'
            ),
        },
    )


def unseed_speed_weight(apps, schema_editor):
    apps.get_model('core', 'AppSetting').objects.filter(key='buying_priority_speed_weight').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0029_condition_shrink_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystats',
            name='sell_through_30_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Of items shelved 30-180 days ago, % sold within 30 days (unsold count against). Empty under 20 items.', max_digits=5, null=True),
        ),
        migrations.RunPython(seed_speed_weight, unseed_speed_weight),
    ]
