# Generated by Django 5.2 on 2026-09-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0031_target_cover_12_weeks'),
        ('inventory', '0100_catalog_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='analysis_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Truck value v2: expected revenue summed line by line (before shrink).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='manifest_analysis',
            field=models.JSONField(blank=True, help_text='Summary from services/manifest_analysis.py: match coverage, hazards, top lines.', null=True),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='hazards',
            field=models.JSONField(blank=True, help_text='Hazard codes for this line.', null=True),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='match_method',
            field=models.CharField(blank=True, db_default='', default='', help_text="How the line was matched: 'upc', 'title' (same title) or 'near' (similar title).", max_length=8),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_manifest_rows', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected revenue per unit, after hazard discounts.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manifestrow',
            name='value_basis',
            field=models.CharField(blank=True, db_default='', default='', help_text="'product' (this product's own sales) or 'category' (the category rate).", max_length=10),
        ),
    ]
