# Generated by Django 5.2 on 2026-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0032_manifest_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expected_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Likely hammer price (retail x seller close ratio, or price x the late bump).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='price_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Buy at or under: the most we can pay and still make the profit factor.', max_digits=12, null=True),
        ),
    ]
