# Generated by Django 5.2 on 2026-09-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0033_price_target'),
        ('inventory', '0100_catalog_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_auctions', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='prediction',
            field=models.JSONField(blank=True, help_text='What we predicted when it was won (revenue, profit, days to sell): the report card.', null=True),
        ),
    ]
