# Generated by Django 5.2 on 2026-09-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0034_won_to_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buyer_notes',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The buyer's own max; the wish list measures room against it (else the price target).", max_digits=12, null=True),
        ),
    ]
