# Generated by Django 5.2 on 2026-02-12 23:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('change_pickup', 'Change Pickup')], max_length=20)),
                ('amount', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='core.worklocation')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('voided', 'Voided')], default='open', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0700'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('split', 'Split')], default='cash', max_length=10)),
                ('cash_tendered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.cart')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Drawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('opening_count', models.JSONField(default=dict)),
                ('opening_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_count', models.JSONField(blank=True, null=True)),
                ('closing_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_drawers', to=settings.AUTH_USER_MODEL)),
                ('current_cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_drawers', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_drawers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('dropped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='pos.drawer')),
            ],
            options={
                'ordering': ['-dropped_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='pos.drawer'),
        ),
        migrations.CreateModel(
            name='DrawerHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_at', models.DateTimeField()),
                ('count', models.JSONField(default=dict)),
                ('counted_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='pos.drawer')),
                ('incoming_cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_in', to=settings.AUTH_USER_MODEL)),
                ('outgoing_cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_out', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-counted_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('printed', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='pos.cart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('starting_cash', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('starting_breakdown', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='core.worklocation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='drawer',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='pos.register'),
        ),
        migrations.CreateModel(
            name='SupplementalDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.JSONField(default=dict)),
                ('current_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('last_counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental_drawer', to='core.worklocation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('draw', 'Draw'), ('return', 'Return'), ('audit_adjustment', 'Audit Adjustment')], max_length=20)),
                ('amount', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_drawer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.drawer')),
                ('supplemental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.supplementaldrawer')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='drawer',
            unique_together={('register', 'date')},
        ),
        migrations.CreateModel(
            name='RevenueGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_goals', to='core.worklocation')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('location', 'date')},
            },
        ),
    ]
