# Generated by Django 5.2 on 2026-02-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashdrop',
            name='dropped_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='current_cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_drawers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawer',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_drawers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawerhandoff',
            name='incoming_cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawerhandoff',
            name='outgoing_cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplementaltransaction',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
