# Generated by Django 5.2 on 2026-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_banktransaction_performed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_db', models.CharField(choices=[('db1', 'DB1 Legacy'), ('db2', 'DB2 Production')], max_length=10)),
                ('legacy_cart_id', models.CharField(max_length=50)),
                ('sale_date', models.DateField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['source_db', 'sale_date'], name='pos_histori_source__61eded_idx')],
                'unique_together': {('source_db', 'legacy_cart_id')},
            },
        ),
    ]
