# Generated by Django 5.2 on 2026-06-25 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


INITIAL_GOALS = [
    ('buying', '10000', 'Weekly dollars bought (PO cost).'),
    ('processing', '25000', 'Weekly value processed to shelf.'),
    ('restoration', '10', 'Weekly TARS jobs completed.'),
    ('retail', 'C', 'Target QA letter grade.'),
]


def seed_department_goals(apps, schema_editor):
    DashboardDepartmentGoal = apps.get_model('pos', 'DashboardDepartmentGoal')
    for department, value, description in INITIAL_GOALS:
        DashboardDepartmentGoal.objects.get_or_create(
            department=department,
            defaults={'value': value, 'description': description},
        )


def unseed_department_goals(apps, schema_editor):
    DashboardDepartmentGoal = apps.get_model('pos', 'DashboardDepartmentGoal')
    DashboardDepartmentGoal.objects.filter(
        department__in=[d for d, _, _ in INITIAL_GOALS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_dashboardsalesgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDepartmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('buying', 'Buying'), ('processing', 'Processing'), ('restoration', 'Restoration'), ('retail', 'Retail QA')], max_length=20, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_department_goals_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_department_goals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.RunPython(seed_department_goals, unseed_department_goals),
    ]
