# Generated by Django 5.2 on 2026-06-29 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_qualityaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAuditForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('intro', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('definition', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('feeds_dashboard', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveIndex(
            model_name='qualityaudit',
            name='pos_quality_audit_type_status_submitted_idx',
        ),
        migrations.AlterField(
            model_name='qualityaudit',
            name='audit_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='qualityauditform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_audit_forms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityauditform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_audit_forms_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityaudit',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='pos.qualityauditform'),
        ),
        migrations.AddIndex(
            model_name='qualityaudit',
            index=models.Index(fields=['form', 'status', '-submitted_at'], name='pos_quality_form_id_5f1523_idx'),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
