# Generated by Django 5.2 on 2026-07-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_delivery_availability_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryavailability',
            new_name='pos_deliver_date_2b2002_idx',
            old_name='pos_deliver_date_0f3f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryjob',
            new_name='pos_deliver_schedul_08985a_idx',
            old_name='pos_deliver_schedul_8a1b2c_idx',
        ),
    ]
