# Generated by Django 5.2 on 2026-07-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0013_deliveryjob_needs_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('en_route', 'En route'), ('completed', 'Completed')], db_index=True, default='preparing', max_length=20)),
                ('phase', models.CharField(choices=[('start', 'Start day'), ('review', 'Review route'), ('load', 'Load & secure'), ('truck', 'Truck photos'), ('calls', 'Customer calls'), ('route', 'Begin route'), ('active', 'Active stops')], default='start', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('route_revision', models.PositiveIntegerField(default=0)),
                ('last_optimized_at', models.DateTimeField(blank=True, null=True)),
                ('maps_url', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='pos.deliveryavailability')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRunStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('next_up', 'Next up'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('secured_at', models.DateTimeField(blank=True, null=True)),
                ('eta_arrive_at', models.DateTimeField(blank=True, null=True)),
                ('eta_window_end_at', models.DateTimeField(blank=True, null=True)),
                ('drive_seconds_from_prev', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_override', models.BooleanField(default=False)),
                ('proof_override_reason', models.CharField(blank=True, default='', max_length=300)),
                ('hold_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_completed', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_stops', to='pos.deliveryjob')),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_loaded', to=settings.AUTH_USER_MODEL)),
                ('proof_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_proof_overridden', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='pos.deliveryrun')),
                ('secured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_secured', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('phase', 'Phase change'), ('load', 'Loaded'), ('secure', 'Secured'), ('photo', 'Photo'), ('call', 'Call'), ('route', 'Route'), ('reorder', 'Reorder'), ('hold', 'Hold'), ('release', 'Release'), ('address', 'Address revision'), ('complete', 'Complete stop'), ('override', 'Proof override'), ('finish', 'Finish run'), ('note', 'Note')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_run_events', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pos.deliveryrun')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pos.deliveryrunstop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('answered_will_be_there', 'Answered - will be there'), ('answered_not_available', 'Answered - not available'), ('no_answer', 'No answer'), ('voicemail_left', 'Voicemail left'), ('text_sent', 'Text sent'), ('wrong_number', 'Wrong number'), ('other', 'Other')], max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_call_attempts', to=settings.AUTH_USER_MODEL)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='pos.deliveryrunstop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('truck', 'Truck photo'), ('delivery_proof', 'Delivery proof'), ('signature', 'Signature')], max_length=20)),
                ('client_photo_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attachments_created', to=settings.AUTH_USER_MODEL)),
                ('s3_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attachments', to='core.s3file')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pos.deliveryrun')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pos.deliveryrunstop')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddressRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('is_apt', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address_revisions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_revisions', to='pos.deliveryjob')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['job', 'is_active'], name='pos_deliver_job_id_4949b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryrun',
            index=models.Index(fields=['date', 'status'], name='pos_deliver_date_a132a3_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrunstop',
            index=models.Index(fields=['run', 'state'], name='pos_deliver_run_id_eb00cc_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrunstop',
            index=models.Index(fields=['run', 'position'], name='pos_deliver_run_id_68a229_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryrunstop',
            unique_together={('run', 'job')},
        ),
        migrations.AddIndex(
            model_name='deliveryrunevent',
            index=models.Index(fields=['run', 'event_type'], name='pos_deliver_run_id_88c6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattachment',
            index=models.Index(fields=['run', 'kind'], name='pos_deliver_run_id_f4a05d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattachment',
            index=models.Index(fields=['stop', 'kind'], name='pos_deliver_stop_id_3fdb23_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattachment',
            index=models.Index(fields=['run', 'client_photo_id'], name='pos_deliver_run_id_c402e8_idx'),
        ),
    ]
