# Generated by Django 5.2 on 2026-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_delivery_run_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrunstop',
            name='scan_verified',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
