# Generated by Django 5.2 on 2026-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_delivery_runstop_scan_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrun',
            name='route_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
