# Generated by Django 5.2 on 2026-07-21 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remap_legacy_phases(apps, schema_editor):
    DeliveryRun = apps.get_model('pos', 'DeliveryRun')
    # review → calls, truck → load, old begin-route screen "route" → active
    DeliveryRun.objects.filter(phase='review').update(phase='calls')
    DeliveryRun.objects.filter(phase='truck').update(phase='load')
    DeliveryRun.objects.filter(phase='route', status='en_route').update(phase='active')
    # Preparing runs stuck on old "route" (ready to depart) map to load so truck/load gate remains
    DeliveryRun.objects.filter(phase='route', status='preparing').update(phase='load')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_delivery_run_route_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrun',
            name='returned_to_store_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='contact_present_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='contact_present_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_contact_present', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_delivered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='return_issue_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='return_issue_notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='return_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='return_reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_return_reconciled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='returned_items_stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='returned_items_stored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_returned_stored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='returned_unloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='returned_unloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_returned_unloaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='phase',
            field=models.CharField(choices=[('start', 'Start day'), ('calls', 'Customer calls'), ('route', 'Confirmed route'), ('load', 'Load & truck photo'), ('active', 'Driving'), ('return', 'Return to store'), ('review', 'Legacy: review'), ('truck', 'Legacy: truck')], default='start', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryrunevent',
            name='event_type',
            field=models.CharField(choices=[('start', 'Start'), ('phase', 'Phase change'), ('load', 'Loaded'), ('secure', 'Secured'), ('photo', 'Photo'), ('call', 'Call'), ('route', 'Route'), ('reorder', 'Reorder'), ('hold', 'Hold'), ('release', 'Release'), ('address', 'Address revision'), ('contact', 'Contact present'), ('delivered', 'Items delivered'), ('complete', 'Complete stop'), ('override', 'Proof override'), ('return', 'Return reconcile'), ('finish', 'Finish run'), ('note', 'Note')], max_length=20),
        ),
        migrations.RunPython(remap_legacy_phases, noop_reverse),
    ]
