# Generated by Django 5.2 on 2026-07-21 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_delivery_driver_workflow_redesign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryattachment',
            name='kind',
            field=models.CharField(
                choices=[
                    ('truck', 'Truck photo'),
                    ('delivery_proof', 'Delivery proof'),
                    ('signature', 'Signature'),
                    ('issue', 'Issue photo'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='deliveryrunevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('start', 'Start'),
                    ('phase', 'Phase change'),
                    ('load', 'Loaded'),
                    ('secure', 'Secured'),
                    ('photo', 'Photo'),
                    ('call', 'Call'),
                    ('route', 'Route'),
                    ('reorder', 'Reorder'),
                    ('hold', 'Hold'),
                    ('release', 'Release'),
                    ('address', 'Address revision'),
                    ('contact', 'Contact present'),
                    ('delivered', 'Items delivered'),
                    ('complete', 'Complete stop'),
                    ('override', 'Proof override'),
                    ('return', 'Return reconcile'),
                    ('finish', 'Finish run'),
                    ('note', 'Note'),
                    ('issue', 'Report issue'),
                    ('reschedule', 'Reschedule job'),
                    ('cancel', 'Cancel job'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='deliveryrunstop',
            name='state',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued'),
                    ('next_up', 'Next up'),
                    ('on_hold', 'On hold'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('rescheduled', 'Rescheduled'),
                ],
                db_index=True,
                default='queued',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='rescheduled_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='delivery_stops_rescheduled',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='rescheduled_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
