# Generated by Django 5.2 on 2026-07-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_delivery_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrun',
            name='departure_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='departure_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs_departure_overridden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='departure_override_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='truck_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrun',
            name='truck_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_runs_truck_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='contact_disposition',
            field=models.CharField(blank=True, choices=[('awaiting_reply', 'Awaiting reply'), ('confirmed', 'Confirmed'), ('reschedule_requested', 'Reschedule requested'), ('cancel_requested', 'Cancel requested'), ('no_answer', 'No answer'), ('voicemail', 'Voicemail'), ('wrong_number', 'Wrong number'), ('other', 'Other')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='contact_disposition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='contact_disposition_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_disposition_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='excluded_unconfirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='excluded_unconfirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stops_excluded_unconfirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstop',
            name='excluded_unconfirmed_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stop_items_loaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='photo_exception_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='photo_exception_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stop_items_photo_exception', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='photo_exception_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='verification_skip_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='verification_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrunstopitem',
            name='verification_skipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_stop_items_verification_skipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryattachment',
            name='kind',
            field=models.CharField(choices=[('truck', 'Truck photo'), ('load_item', 'In-truck item photo'), ('delivery_proof', 'Delivery proof'), ('signature', 'Signature'), ('issue', 'Issue photo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverycallattempt',
            name='action',
            field=models.CharField(blank=True, choices=[('call_placed', 'Call placed'), ('composer_opened', 'Composer opened'), ('text_marked_sent', 'Text marked sent')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='deliverycallattempt',
            name='result',
            field=models.CharField(blank=True, choices=[('answered_will_be_there', 'Answered — will be there'), ('answered_not_available', 'Answered — not available'), ('no_answer', 'No answer'), ('voicemail_left', 'Voicemail left'), ('text_sent', 'Text sent'), ('wrong_number', 'Wrong number'), ('other', 'Other')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='deliveryrun',
            name='phase',
            field=models.CharField(choices=[('start', 'Start day'), ('calls', 'Customer calls'), ('load', 'Load items'), ('truck', 'Close truck'), ('route', 'Confirmed route'), ('active', 'Driving'), ('return', 'Return to store'), ('review', 'Legacy: review')], default='start', max_length=20),
        ),
    ]
