# Generated by Django 5.2 on 2026-09-25 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_retail_goal_plus_minus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='thrift_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Thrift+ store credit and banked rewards spent on this sale; cash or card covers the rest of the total.', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartline',
            name='thrift_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Thrift+: the member rebate taken off this line today (set by thriftplus.services.register.sync).', max_digits=10),
        ),
    ]
