# Generated by Django 5.2 on 2026-10-07 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SETTING = {'payroll_deduction': False, 'payroll_max_percent': 25, 'thrift_plus_free': False}


def seed(apps, schema_editor):
    """The owner's staff-purchase switches, both off (owner, 2026-10-07: start with this off)."""
    AppSetting = apps.get_model('core', 'AppSetting')
    AppSetting.objects.get_or_create(key='pos.staff_purchases', defaults={
        'value': SETTING,
        'description': 'Staff purchases: payroll deduction at the register (cap: % of the last paycheck), and Thrift+ free for staff.',
    })


def unseed(apps, schema_editor):
    apps.get_model('core', 'AppSetting').objects.filter(key='pos.staff_purchases').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_thrift_plus_fields'),
        ('core', '0011_ai_model_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payroll_employee',
            field=models.ForeignKey(blank=True, help_text='Payroll deduction: whose next paycheck this sale comes out of.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('split', 'Split'), ('payroll', 'Payroll deduction')], default='cash', max_length=10),
        ),
        migrations.CreateModel(
            name='PayrollDeductionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marked_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('employee', 'period_start')},
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
